1.18.6
/usr/lib
/usr/lib/libcairo-script-interpreter.so.2
/usr/lib/libcairo-gobject.so
/usr/lib/cairo
/usr/lib/cairo/libcairo-fdr.so
/usr/lib/cairo/libcairo-trace.so
/usr/lib/libcairo-gobject.so.2
/usr/lib/pkgconfig
/usr/lib/pkgconfig/cairo-png.pc
/usr/lib/pkgconfig/cairo-ft.pc
/usr/lib/pkgconfig/cairo-tee.pc
/usr/lib/pkgconfig/cairo-xlib-xrender.pc
/usr/lib/pkgconfig/cairo-xcb-shm.pc
/usr/lib/pkgconfig/cairo.pc
/usr/lib/pkgconfig/cairo-ps.pc
/usr/lib/pkgconfig/cairo-gobject.pc
/usr/lib/pkgconfig/cairo-script-interpreter.pc
/usr/lib/pkgconfig/cairo-pdf.pc
/usr/lib/pkgconfig/cairo-xlib.pc
/usr/lib/pkgconfig/cairo-xcb.pc
/usr/lib/pkgconfig/cairo-fc.pc
/usr/lib/pkgconfig/cairo-script.pc
/usr/lib/pkgconfig/expat.pc
/usr/lib/pkgconfig/cairo-svg.pc
/usr/lib/libcairo.so
/usr/lib/libcairo-script-interpreter.so
/usr/lib/libcairo-gobject.so.2.11806.6
/usr/lib/libcairo.so.2
/usr/lib/libcairo-script-interpreter.so.2.11806.6
/usr/lib/libcairo.so.2.11806.6
/usr/lib/cmake/expat-2.8.5
/usr/lib/cmake/expat-2.8.5/expat.cmake
/usr/lib/cmake/expat-2.8.5/expat-config.cmake
/usr/lib/cmake/expat-2.8.5/expat-config-version.cmake
/usr/lib/cmake/expat-2.8.5/expat-noconfig.cmake
/usr/lib/libexpat.so.1.12.5
/usr/share/doc
/usr/share/doc/expat-2.8.5
/usr/share/doc/expat-2.8.5/AUTHORS
/usr/share/doc/expat-2.8.5/changelog
/usr/bin
/usr/bin/xmlwf
/usr/bin/cairo-trace
/usr/include
/usr/include/cairo
/usr/include/cairo/cairo-xcb.h
/usr/include/cairo/cairo-version.h
/usr/include/cairo/cairo-script.h
/usr/include/cairo/cairo-deprecated.h
/usr/include/cairo/cairo-ps.h
/usr/include/cairo/cairo-xlib.h
/usr/include/cairo/cairo-features.h
/usr/include/cairo/cairo-script-interpreter.h
/usr/include/cairo/cairo-gobject.h
/usr/include/cairo/cairo-ft.h
/usr/include/cairo/cairo.h
/usr/include/cairo/cairo-svg.h
/usr/include/cairo/cairo-pdf.h
/usr/include/cairo/cairo-xlib-xrender.h
/usr/include/cairo/cairo-tee.h
/usr/include/expat_config.h
/usr/include/expat_external.h
/usr/include/expat.h
/lib/cairo
/lib/pkgconfig
/lib/libcairo.so.2
/lib/libcairo.so
/lib/libcairo-gobject.so.2
/lib/libcairo-gobject.so
/lib/libcairo-script-interpreter.so.2
/lib/libcairo-script-interpreter.so
