2.6.4
/usr/lib
/usr/lib/libfl.la
/usr/lib/libfl.so.2
/usr/lib/libfl.so.2.0.0
/usr/lib/libfl.so
/usr/share/doc/flex-2.6.4
/usr/share/doc/flex-2.6.4/COPYING
/usr/share/doc/flex-2.6.4/AUTHORS
/usr/share/doc/flex-2.6.4/ONEWS
/usr/share/doc/flex-2.6.4/NEWS
/usr/share/doc/flex-2.6.4/README.md
/usr/share/locale/en@quot/LC_MESSAGES
/usr/share/locale/en@quot/LC_MESSAGES/flex.mo
/usr/share/locale/ro/LC_MESSAGES
/usr/share/locale/ro/LC_MESSAGES/flex.mo
/usr/share/locale/en@boldquot/LC_MESSAGES
/usr/share/locale/en@boldquot/LC_MESSAGES/flex.mo
/usr/share/locale/hr/LC_MESSAGES
/usr/share/locale/hr/LC_MESSAGES/flex.mo
/usr/share/locale/da/LC_MESSAGES
/usr/share/locale/da/LC_MESSAGES/flex.mo
/usr/share/locale/tr/LC_MESSAGES
/usr/share/locale/tr/LC_MESSAGES/flex.mo
/usr/share/locale/vi/LC_MESSAGES
/usr/share/locale/vi/LC_MESSAGES/flex.mo
/usr/share/locale/sr/LC_MESSAGES
/usr/share/locale/sr/LC_MESSAGES/flex.mo
/usr/share/locale/nl/LC_MESSAGES
/usr/share/locale/nl/LC_MESSAGES/flex.mo
/usr/share/locale/fr/LC_MESSAGES
/usr/share/locale/fr/LC_MESSAGES/flex.mo
/usr/share/locale/ko/LC_MESSAGES
/usr/share/locale/ko/LC_MESSAGES/flex.mo
/usr/share/locale/zh_CN/LC_MESSAGES
/usr/share/locale/zh_CN/LC_MESSAGES/flex.mo
/usr/share/locale/es/LC_MESSAGES
/usr/share/locale/es/LC_MESSAGES/flex.mo
/usr/share/locale/eo/LC_MESSAGES
/usr/share/locale/eo/LC_MESSAGES/flex.mo
/usr/share/locale/fi/LC_MESSAGES
/usr/share/locale/fi/LC_MESSAGES/flex.mo
/usr/share/locale/zh_TW/LC_MESSAGES
/usr/share/locale/zh_TW/LC_MESSAGES/flex.mo
/usr/share/locale/de/LC_MESSAGES
/usr/share/locale/de/LC_MESSAGES/flex.mo
/usr/share/locale/ru/LC_MESSAGES
/usr/share/locale/ru/LC_MESSAGES/flex.mo
/usr/share/locale/pl/LC_MESSAGES
/usr/share/locale/pl/LC_MESSAGES/flex.mo
/usr/share/locale/sv/LC_MESSAGES
/usr/share/locale/sv/LC_MESSAGES/flex.mo
/usr/share/locale/ga/LC_MESSAGES
/usr/share/locale/ga/LC_MESSAGES/flex.mo
/usr/share/locale/pt_BR/LC_MESSAGES
/usr/share/locale/pt_BR/LC_MESSAGES/flex.mo
/usr/share/locale/ca/LC_MESSAGES
/usr/share/locale/ca/LC_MESSAGES/flex.mo
/usr/share/man/man1
/usr/share/man/man1/flex.1
/usr/share/man/man1/lex.1
/usr/share/info
/usr/share/info/flex.info-2
/usr/share/info/flex.info-1
/usr/share/info/dir
/usr/share/info/flex.info
/usr/bin
/usr/bin/flex++
/usr/bin/flex
/usr/bin/lex
/usr/include
/usr/include/FlexLexer.h
