5.4.1
/usr/lib/gawk
/usr/lib/gawk/rwarray.so
/usr/lib/gawk/time.so
/usr/lib/gawk/filefuncs.so
/usr/lib/gawk/intdiv.so
/usr/lib/gawk/inplace.so
/usr/lib/gawk/revtwoway.so
/usr/lib/gawk/ordchr.so
/usr/lib/gawk/revoutput.so
/usr/lib/gawk/fork.so
/usr/lib/gawk/readfile.so
/usr/lib/gawk/readdir.so
/usr/lib/gawk/fnmatch.so
/usr/share/awk
/usr/share/awk/processarray.awk
/usr/share/awk/libintl.awk
/usr/share/awk/isnumeric.awk
/usr/share/awk/round.awk
/usr/share/awk/bits2str.awk
/usr/share/awk/assert.awk
/usr/share/awk/ord.awk
/usr/share/awk/getopt.awk
/usr/share/awk/rewind.awk
/usr/share/awk/walkarray.awk
/usr/share/awk/noassign.awk
/usr/share/awk/cliff_rand.awk
/usr/share/awk/shellquote.awk
/usr/share/awk/inplace.awk
/usr/share/awk/zerofile.awk
/usr/share/awk/tocsv.awk
/usr/share/awk/ns_passwd.awk
/usr/share/awk/strtonum.awk
/usr/share/awk/passwd.awk
/usr/share/awk/have_mpfr.awk
/usr/share/awk/quicksort.awk
/usr/share/awk/join.awk
/usr/share/awk/ctime.awk
/usr/share/awk/intdiv0.awk
/usr/share/awk/gettime.awk
/usr/share/awk/readfile.awk
/usr/share/awk/readable.awk
/usr/share/awk/group.awk
/usr/share/awk/ftrans.awk
/usr/share/locale/ro/LC_MESSAGES
/usr/share/locale/ro/LC_MESSAGES/gawk.mo
/usr/share/locale/it/LC_MESSAGES
/usr/share/locale/it/LC_MESSAGES/gawk.mo
/usr/share/locale/tr/LC_MESSAGES
/usr/share/locale/tr/LC_MESSAGES/gawk.mo
/usr/share/locale/sr/LC_MESSAGES
/usr/share/locale/sr/LC_MESSAGES/gawk.mo
/usr/share/locale/nl/LC_MESSAGES
/usr/share/locale/nl/LC_MESSAGES/gawk.mo
/usr/share/locale/fr/LC_MESSAGES
/usr/share/locale/fr/LC_MESSAGES/gawk.mo
/usr/share/locale/ko/LC_MESSAGES
/usr/share/locale/ko/LC_MESSAGES/gawk.mo
/usr/share/locale/ka/LC_MESSAGES
/usr/share/locale/ka/LC_MESSAGES/gawk.mo
/usr/share/locale/zh_CN/LC_MESSAGES
/usr/share/locale/zh_CN/LC_MESSAGES/gawk.mo
/usr/share/locale/es/LC_MESSAGES
/usr/share/locale/es/LC_MESSAGES/gawk.mo
/usr/share/locale/de/LC_MESSAGES
/usr/share/locale/de/LC_MESSAGES/gawk.mo
/usr/share/locale/he/LC_MESSAGES
/usr/share/locale/he/LC_MESSAGES/gawk.mo
/usr/share/locale/id/LC_MESSAGES
/usr/share/locale/id/LC_MESSAGES/gawk.mo
/usr/share/locale/bg/LC_MESSAGES
/usr/share/locale/bg/LC_MESSAGES/gawk.mo
/usr/share/locale/pt/LC_MESSAGES
/usr/share/locale/pt/LC_MESSAGES/gawk.mo
/usr/share/locale/pl/LC_MESSAGES
/usr/share/locale/pl/LC_MESSAGES/gawk.mo
/usr/share/locale/uk/LC_MESSAGES
/usr/share/locale/uk/LC_MESSAGES/gawk.mo
/usr/share/locale/ar/LC_MESSAGES
/usr/share/locale/ar/LC_MESSAGES/gawk.mo
/usr/share/locale/sv/LC_MESSAGES
/usr/share/locale/sv/LC_MESSAGES/gawk.mo
/usr/share/locale/pt_BR/LC_MESSAGES
/usr/share/locale/pt_BR/LC_MESSAGES/gawk.mo
/usr/share/man/man1
/usr/share/man/man1/gawk.1
/usr/share/man/man1/gawkbug.1
/usr/share/man/man1/pm-gawk.1
/usr/share/man/man3
/usr/share/man/man3/fnmatch.3am
/usr/share/man/man3/fork.3am
/usr/share/man/man3/inplace.3am
/usr/share/man/man3/intdiv.3am
/usr/share/man/man3/ordchr.3am
/usr/share/man/man3/readdir.3am
/usr/share/man/man3/readfile.3am
/usr/share/man/man3/revoutput.3am
/usr/share/man/man3/revtwoway.3am
/usr/share/man/man3/rwarray.3am
/usr/share/man/man3/time.3am
/usr/share/man/man3/filefuncs.3am
/usr/share/info
/usr/share/info/gawk_process-flow.png
/usr/share/info/gawk_statist.jpg
/usr/share/info/gawkworkflow.info
/usr/share/info/gawk_general-program.png
/usr/share/info/gawk_api-figure2.png
/usr/share/info/dir
/usr/share/info/pm-gawk.info
/usr/share/info/gawk.info
/usr/share/info/gawkinet.info
/usr/share/info/gawk_api-figure1.png
/usr/share/info/gawknotes.info
/usr/share/info/gawk_api-figure3.png
/usr/share/info/gawk_array-elements.png
/usr/bin
/usr/bin/gawk
/usr/bin/gawkbug
/usr/libexec/awk
/usr/libexec/awk/pwcat
/usr/libexec/awk/grcat
/usr/include
/usr/include/gawkapi.h
