1.90.0
/usr/lib
/usr/lib/libgjs.so.0.0.0
/usr/lib/pkgconfig
/usr/lib/pkgconfig/gjs-1.0.pc
/usr/lib/gjs/girepository-1.0
/usr/lib/gjs/girepository-1.0/GjsPrivate-1.0.typelib
/usr/lib/libgjs.so.0
/usr/lib/libgjs.so
/usr/share/installed-tests/gjs
/usr/share/installed-tests/gjs/testGDBus.test
/usr/share/installed-tests/gjs/throw.test
/usr/share/installed-tests/gjs/down-up.test
/usr/share/installed-tests/gjs/throw-ignored.test
/usr/share/installed-tests/gjs/testNamespace.test
/usr/share/installed-tests/gjs/testGObjectValue.test
/usr/share/installed-tests/gjs/testGlobal.test
/usr/share/installed-tests/gjs/testGIMarshalling.test
/usr/share/installed-tests/gjs/breakpoint.test
/usr/share/installed-tests/gjs/testGLib.test
/usr/share/installed-tests/gjs/testLegacyGtk.test
/usr/share/installed-tests/gjs/testGtk4.test
/usr/share/installed-tests/gjs/keys.test
/usr/share/installed-tests/gjs/until.test
/usr/share/installed-tests/gjs/list.test
/usr/share/installed-tests/gjs/testTweener.test
/usr/share/installed-tests/gjs/testParamSpec.test
/usr/share/installed-tests/gjs/testPrint.test
/usr/share/installed-tests/gjs/sourcemap-dynamic-module.test
/usr/share/installed-tests/gjs/testGio.test
/usr/share/installed-tests/gjs/sourcemap-separate-module.test
/usr/share/installed-tests/gjs/testGtk3.test
/usr/share/installed-tests/gjs/testPackage.test
/usr/share/installed-tests/gjs/testLegacyByteArray.test
/usr/share/installed-tests/gjs/testLegacyGObject.test
/usr/share/installed-tests/gjs/testWarnings.sh.test
/usr/share/installed-tests/gjs/detach.test
/usr/share/installed-tests/gjs/testWarnLib.test
/usr/share/installed-tests/gjs/testGObject.test
/usr/share/installed-tests/gjs/testGTypeClass.test
/usr/share/installed-tests/gjs/testCairo.test
/usr/share/installed-tests/gjs/testPromise.test
/usr/share/installed-tests/gjs/set.test
/usr/share/installed-tests/gjs/testGettext.test
/usr/share/installed-tests/gjs/testFundamental.test
/usr/share/installed-tests/gjs/sourcemap-inlined.test
/usr/share/installed-tests/gjs/testAsync.test
/usr/share/installed-tests/gjs/testExceptions.test
/usr/share/installed-tests/gjs/testCommandLine.sh.test
/usr/share/installed-tests/gjs/testEncoding.test
/usr/share/installed-tests/gjs/testConsole.test
/usr/share/installed-tests/gjs/frame.test
/usr/share/installed-tests/gjs/testFormat.test
/usr/share/installed-tests/gjs/testGObjectInterface.test
/usr/share/installed-tests/gjs/step.test
/usr/share/installed-tests/gjs/return.test
/usr/share/installed-tests/gjs/next.test
/usr/share/installed-tests/gjs/testGObjectClass.test
/usr/share/installed-tests/gjs/testCommandLineModules.sh.test
/usr/share/installed-tests/gjs/testAsyncMainloop.test
/usr/share/installed-tests/gjs/sourcemap-inlined-module.test
/usr/share/installed-tests/gjs/testMainloop.test
/usr/share/installed-tests/gjs/testGtk4Warnings.sh.test
/usr/share/installed-tests/gjs/testGObjectDestructionAccess.test
/usr/share/installed-tests/gjs/testImporter.test
/usr/share/installed-tests/gjs/sourcemap-separate.test
/usr/share/installed-tests/gjs/testUtility.test
/usr/share/installed-tests/gjs/testOverrides.test
/usr/share/installed-tests/gjs/finish.test
/usr/share/installed-tests/gjs/testImporter2.test
/usr/share/installed-tests/gjs/testSystem.test
/usr/share/installed-tests/gjs/testLegacyCairo.test
/usr/share/installed-tests/gjs/testSignals.test
/usr/share/installed-tests/gjs/delete.test
/usr/share/installed-tests/gjs/testTimers.test
/usr/share/installed-tests/gjs/quit.test
/usr/share/installed-tests/gjs/testself.test
/usr/share/installed-tests/gjs/testLegacyClass.test
/usr/share/installed-tests/gjs/continue.test
/usr/share/installed-tests/gjs/testIntrospection.test
/usr/share/installed-tests/gjs/testGdkPixbuf.test
/usr/share/installed-tests/gjs/testRegress.test
/usr/share/installed-tests/gjs/testESModules.test
/usr/share/installed-tests/gjs/lastvalues.test
/usr/share/installed-tests/gjs/testLang.test
/usr/share/installed-tests/gjs/testWeakRef.test
/usr/share/installed-tests/gjs/backtrace.test
/usr/share/installed-tests/gjs/testGLibLogWriter.test
/usr/share/installed-tests/gjs/print.test
/usr/share/glib-2.0/schemas
/usr/share/glib-2.0/schemas/org.gnome.GjsTest.gschema.xml
/usr/share/glib-2.0/schemas/gschemas.compiled
/usr/share/gjs-1.0/lsan
/usr/share/gjs-1.0/lsan/lsan.supp
/usr/share/gjs-1.0/valgrind
/usr/share/gjs-1.0/valgrind/gjs.supp
/usr/bin
/usr/bin/gjs
/usr/bin/gjs-console
/usr/libexec/installed-tests/gjs
/usr/libexec/installed-tests/gjs/scripts
/usr/libexec/installed-tests/gjs/scripts/testGtk4Warnings.sh
/usr/libexec/installed-tests/gjs/scripts/testWarnings.sh
/usr/libexec/installed-tests/gjs/scripts/testCommandLine.sh
/usr/libexec/installed-tests/gjs/scripts/testCommandLineModules.sh
/usr/libexec/installed-tests/gjs/GjsTestTools-1.0.typelib
/usr/libexec/installed-tests/gjs/minijasmine
/usr/libexec/installed-tests/gjs/libgimarshallingtests.so
/usr/libexec/installed-tests/gjs/libwarnlib.so
/usr/libexec/installed-tests/gjs/Utility-1.0.typelib
/usr/libexec/installed-tests/gjs/Regress-1.0.typelib
/usr/libexec/installed-tests/gjs/GIMarshallingTests-1.0.typelib
/usr/libexec/installed-tests/gjs/debugger-test.sh
/usr/libexec/installed-tests/gjs/libgjstesttools.so
/usr/libexec/installed-tests/gjs/debugger
/usr/libexec/installed-tests/gjs/debugger/until.debugger.output
/usr/libexec/installed-tests/gjs/debugger/quit.debugger.js
/usr/libexec/installed-tests/gjs/debugger/breakpoint.debugger
/usr/libexec/installed-tests/gjs/debugger/until.debugger
/usr/libexec/installed-tests/gjs/debugger/set.debugger
/usr/libexec/installed-tests/gjs/debugger/keys.debugger.output
/usr/libexec/installed-tests/gjs/debugger/sourcemap-inlined.debugger.output
/usr/libexec/installed-tests/gjs/debugger/lastvalues.debugger
/usr/libexec/installed-tests/gjs/debugger/step.debugger.output
/usr/libexec/installed-tests/gjs/debugger/quit.debugger.output
/usr/libexec/installed-tests/gjs/debugger/next.debugger.js
/usr/libexec/installed-tests/gjs/debugger/list.debugger
/usr/libexec/installed-tests/gjs/debugger/list.debugger.output
/usr/libexec/installed-tests/gjs/debugger/step.debugger
/usr/libexec/installed-tests/gjs/debugger/down-up.debugger.output
/usr/libexec/installed-tests/gjs/debugger/throw.debugger
/usr/libexec/installed-tests/gjs/debugger/finish.debugger.output
/usr/libexec/installed-tests/gjs/debugger/print.debugger.output
/usr/libexec/installed-tests/gjs/debugger/down-up.debugger.js
/usr/libexec/installed-tests/gjs/debugger/sourcemap-separate.debugger.output
/usr/libexec/installed-tests/gjs/debugger/set.debugger.js
/usr/libexec/installed-tests/gjs/debugger/sourcemap-inlined-module.debugger
/usr/libexec/installed-tests/gjs/debugger/next.debugger
/usr/libexec/installed-tests/gjs/debugger/detach.debugger
/usr/libexec/installed-tests/gjs/debugger/print.debugger.js
/usr/libexec/installed-tests/gjs/debugger/breakpoint.debugger.output
/usr/libexec/installed-tests/gjs/debugger/detach.debugger.output
/usr/libexec/installed-tests/gjs/debugger/next.debugger.output
/usr/libexec/installed-tests/gjs/debugger/frame.debugger.js
/usr/libexec/installed-tests/gjs/debugger/lastvalues.debugger.js
/usr/libexec/installed-tests/gjs/debugger/throw.debugger.output
/usr/libexec/installed-tests/gjs/debugger/continue.debugger
/usr/libexec/installed-tests/gjs/debugger/finish.debugger
/usr/libexec/installed-tests/gjs/debugger/backtrace.debugger.output
/usr/libexec/installed-tests/gjs/debugger/breakpoint.debugger.js
/usr/libexec/installed-tests/gjs/debugger/throw-ignored.debugger
/usr/libexec/installed-tests/gjs/debugger/frame.debugger.output
/usr/libexec/installed-tests/gjs/debugger/sourcemap-inlined-module.debugger.js
/usr/libexec/installed-tests/gjs/debugger/throw.debugger.js
/usr/libexec/installed-tests/gjs/debugger/sourcemap-separate-module.debugger
/usr/libexec/installed-tests/gjs/debugger/step.debugger.js
/usr/libexec/installed-tests/gjs/debugger/sourcemap-dynamic-module.debugger.js
/usr/libexec/installed-tests/gjs/debugger/return.debugger.output
/usr/libexec/installed-tests/gjs/debugger/lastvalues.debugger.output
/usr/libexec/installed-tests/gjs/debugger/keys.debugger.js
/usr/libexec/installed-tests/gjs/debugger/continue.debugger.js
/usr/libexec/installed-tests/gjs/debugger/until.debugger.js
/usr/libexec/installed-tests/gjs/debugger/backtrace.debugger
/usr/libexec/installed-tests/gjs/debugger/backtrace.debugger.js
/usr/libexec/installed-tests/gjs/debugger/detach.debugger.js
/usr/libexec/installed-tests/gjs/debugger/continue.debugger.output
/usr/libexec/installed-tests/gjs/debugger/delete.debugger
/usr/libexec/installed-tests/gjs/debugger/sourcemap-dynamic-module.debugger
/usr/libexec/installed-tests/gjs/debugger/finish.debugger.js
/usr/libexec/installed-tests/gjs/debugger/frame.debugger
/usr/libexec/installed-tests/gjs/debugger/sourcemap-inlined-module.debugger.output
/usr/libexec/installed-tests/gjs/debugger/delete.debugger.js
/usr/libexec/installed-tests/gjs/debugger/sourcemap-separate.debugger.js
/usr/libexec/installed-tests/gjs/debugger/delete.debugger.output
/usr/libexec/installed-tests/gjs/debugger/keys.debugger
/usr/libexec/installed-tests/gjs/debugger/throw-ignored.debugger.output
/usr/libexec/installed-tests/gjs/debugger/throw-ignored.debugger.js
/usr/libexec/installed-tests/gjs/debugger/return.debugger.js
/usr/libexec/installed-tests/gjs/debugger/sourcemap-dynamic-module.debugger.output
/usr/libexec/installed-tests/gjs/debugger/sourcemap-number-module.js
/usr/libexec/installed-tests/gjs/debugger/sourcemap-inlined.debugger
/usr/libexec/installed-tests/gjs/debugger/quit.debugger
/usr/libexec/installed-tests/gjs/debugger/sourcemap-separate-module.debugger.output
/usr/libexec/installed-tests/gjs/debugger/sourcemap-inlined.debugger.js
/usr/libexec/installed-tests/gjs/debugger/sourcemap-separate.debugger
/usr/libexec/installed-tests/gjs/debugger/down-up.debugger
/usr/libexec/installed-tests/gjs/debugger/return.debugger
/usr/libexec/installed-tests/gjs/debugger/sourcemap-separate-module.debugger.js
/usr/libexec/installed-tests/gjs/debugger/print.debugger
/usr/libexec/installed-tests/gjs/debugger/set.debugger.output
/usr/libexec/installed-tests/gjs/debugger/list.debugger.js
/usr/libexec/installed-tests/gjs/WarnLib-1.0.typelib
/usr/libexec/installed-tests/gjs/js
/usr/libexec/installed-tests/gjs/js/testPromise.js
/usr/libexec/installed-tests/gjs/js/testPrint.js
/usr/libexec/installed-tests/gjs/js/testself.js
/usr/libexec/installed-tests/gjs/js/testGtk3.js
/usr/libexec/installed-tests/gjs/js/testIntrospection.js
/usr/libexec/installed-tests/gjs/js/testTweener.js
/usr/libexec/installed-tests/gjs/js/testAsyncMainloop.js
/usr/libexec/installed-tests/gjs/js/testOverrides.js
/usr/libexec/installed-tests/gjs/js/matchers.js
/usr/libexec/installed-tests/gjs/js/testCairo.js
/usr/libexec/installed-tests/gjs/js/testImporter2.js
/usr/libexec/installed-tests/gjs/js/testGObjectDestructionAccess.js
/usr/libexec/installed-tests/gjs/js/testConsole.js
/usr/libexec/installed-tests/gjs/js/testMainloop.js
/usr/libexec/installed-tests/gjs/js/testGObjectValue.js
/usr/libexec/installed-tests/gjs/js/testWarnLib.js
/usr/libexec/installed-tests/gjs/js/testSignals.js
/usr/libexec/installed-tests/gjs/js/testNamespace.js
/usr/libexec/installed-tests/gjs/js/testGdkPixbuf.js
/usr/libexec/installed-tests/gjs/js/testGettext.js
/usr/libexec/installed-tests/gjs/js/testUtility.js
/usr/libexec/installed-tests/gjs/js/testTimers.js
/usr/libexec/installed-tests/gjs/js/testLegacyClass.js
/usr/libexec/installed-tests/gjs/js/testParamSpec.js
/usr/libexec/installed-tests/gjs/js/testESModules.js
/usr/libexec/installed-tests/gjs/js/testGlobal.js
/usr/libexec/installed-tests/gjs/js/testFundamental.js
/usr/libexec/installed-tests/gjs/js/testLang.js
/usr/libexec/installed-tests/gjs/js/testGLib.js
/usr/libexec/installed-tests/gjs/js/testImporter.js
/usr/libexec/installed-tests/gjs/js/testGIMarshalling.js
/usr/libexec/installed-tests/gjs/js/testLegacyGObject.js
/usr/libexec/installed-tests/gjs/js/testGio.js
/usr/libexec/installed-tests/gjs/js/testGObject.js
/usr/libexec/installed-tests/gjs/js/testRegress.js
/usr/libexec/installed-tests/gjs/js/testGObjectClass.js
/usr/libexec/installed-tests/gjs/js/testSystem.js
/usr/libexec/installed-tests/gjs/js/testExceptions.js
/usr/libexec/installed-tests/gjs/js/testLegacyByteArray.js
/usr/libexec/installed-tests/gjs/js/testGObjectInterface.js
/usr/libexec/installed-tests/gjs/js/modules
/usr/libexec/installed-tests/gjs/js/modules/say.js
/usr/libexec/installed-tests/gjs/js/modules/modunicode.js
/usr/libexec/installed-tests/gjs/js/modules/sideEffect2.js
/usr/libexec/installed-tests/gjs/js/modules/sideEffect4.js
/usr/libexec/installed-tests/gjs/js/modules/overrides
/usr/libexec/installed-tests/gjs/js/modules/overrides/GIMarshallingTests.js
/usr/libexec/installed-tests/gjs/js/modules/encodings.json
/usr/libexec/installed-tests/gjs/js/modules/networkURI.js
/usr/libexec/installed-tests/gjs/js/modules/dynamic.js
/usr/libexec/installed-tests/gjs/js/modules/exports.js
/usr/libexec/installed-tests/gjs/js/modules/alwaysThrows.js
/usr/libexec/installed-tests/gjs/js/modules/mutualImport
/usr/libexec/installed-tests/gjs/js/modules/mutualImport/b.js
/usr/libexec/installed-tests/gjs/js/modules/mutualImport/a.js
/usr/libexec/installed-tests/gjs/js/modules/foobar.js
/usr/libexec/installed-tests/gjs/js/modules/subA/subB
/usr/libexec/installed-tests/gjs/js/modules/subA/subB/__init__.js
/usr/libexec/installed-tests/gjs/js/modules/subA/subB/foobar.js
/usr/libexec/installed-tests/gjs/js/modules/subA/subB/baz.js
/usr/libexec/installed-tests/gjs/js/modules/scaryURI.js
/usr/libexec/installed-tests/gjs/js/modules/badOverrides
/usr/libexec/installed-tests/gjs/js/modules/badOverrides/Regress.js
/usr/libexec/installed-tests/gjs/js/modules/badOverrides/WarnLib.js
/usr/libexec/installed-tests/gjs/js/modules/badOverrides/GIMarshallingTests.js
/usr/libexec/installed-tests/gjs/js/modules/badOverrides/Gio.js
/usr/libexec/installed-tests/gjs/js/modules/importmeta.js
/usr/libexec/installed-tests/gjs/js/modules/subErrorInit
/usr/libexec/installed-tests/gjs/js/modules/subErrorInit/__init__.js
/usr/libexec/installed-tests/gjs/js/modules/subBadInit
/usr/libexec/installed-tests/gjs/js/modules/subBadInit/__init__.js
/usr/libexec/installed-tests/gjs/js/modules/sideEffect.js
/usr/libexec/installed-tests/gjs/js/modules/data.txt
/usr/libexec/installed-tests/gjs/js/modules/sloppy.js
/usr/libexec/installed-tests/gjs/js/modules/lexicalScope.js
/usr/libexec/installed-tests/gjs/js/modules/sideEffect3.js
/usr/libexec/installed-tests/gjs/js/modules/badOverrides2
/usr/libexec/installed-tests/gjs/js/modules/badOverrides2/Regress.js
/usr/libexec/installed-tests/gjs/js/modules/badOverrides2/WarnLib.js
/usr/libexec/installed-tests/gjs/js/modules/badOverrides2/GIMarshallingTests.js
/usr/libexec/installed-tests/gjs/js/modules/badOverrides2/Gio.js
/usr/libexec/installed-tests/gjs/js/modules/greet.js
/usr/libexec/installed-tests/gjs/js/testGLibLogWriter.js
/usr/libexec/installed-tests/gjs/js/testGTypeClass.js
/usr/libexec/installed-tests/gjs/js/testGDBus.js
/usr/libexec/installed-tests/gjs/js/testLegacyCairo.js
/usr/libexec/installed-tests/gjs/js/testEncoding.js
/usr/libexec/installed-tests/gjs/js/testPackage.js
/usr/libexec/installed-tests/gjs/js/testWeakRef.js
/usr/libexec/installed-tests/gjs/js/testLegacyGtk.js
/usr/libexec/installed-tests/gjs/js/testAsync.js
/usr/libexec/installed-tests/gjs/js/testFormat.js
/usr/libexec/installed-tests/gjs/js/testGtk4.js
/usr/libexec/installed-tests/gjs/libregress.so
/usr/libexec/installed-tests/gjs/libutility.so
/usr/libexec/installed-tests/gjs/RegressUnix-1.0.typelib
/usr/include/gjs-1.0/gjs
/usr/include/gjs-1.0/gjs/gjs.h
/usr/include/gjs-1.0/gjs/context.h
/usr/include/gjs-1.0/gjs/macros.h
/usr/include/gjs-1.0/gjs/error-types.h
/usr/include/gjs-1.0/gjs/mem.h
/usr/include/gjs-1.0/gjs/profiler.h
/usr/include/gjs-1.0/gjs/coverage.h
/lib/gjs/girepository-1.0
/lib/pkgconfig
/lib/libgjs.so.0
/lib/libgjs.so
