6.0.5
/usr/share/doc/gnuplot-6.0.5/RELEASE_NOTES
/usr/share/doc/gnuplot-6.0.5/NEWS
/usr/share/doc/gnuplot-6.0.5/Copyright
/usr/share/gnuplot/gnuplot/6.0
/usr/share/gnuplot/gnuplot/6.0/colors_mono.gp
/usr/share/gnuplot/gnuplot/6.0/lua
/usr/share/gnuplot/gnuplot/6.0/lua/gnuplot-tikz.lua
/usr/share/gnuplot/gnuplot/6.0/gnuplotrc
/usr/share/gnuplot/gnuplot/6.0/gnuplot.gih
/usr/share/gnuplot/gnuplot/6.0/PostScript
/usr/share/gnuplot/gnuplot/6.0/PostScript/cp437.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/cp852.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/8859-9.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/cp1251.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/cp850.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/aglfn.txt
/usr/share/gnuplot/gnuplot/6.0/PostScript/8859-1.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/utf-8.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/koi8u.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/koi8r.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/prologue.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/cp1250.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/8859-15.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/cp1252.ps
/usr/share/gnuplot/gnuplot/6.0/PostScript/8859-2.ps
/usr/share/gnuplot/gnuplot/6.0/app-defaults
/usr/share/gnuplot/gnuplot/6.0/app-defaults/Gnuplot
/usr/share/gnuplot/gnuplot/6.0/colors_podo.gp
/usr/share/gnuplot/gnuplot/6.0/colors_default.gp
/usr/share/gnuplot/gnuplot/6.0/js
/usr/share/gnuplot/gnuplot/6.0/js/return.png
/usr/share/gnuplot/gnuplot/6.0/js/gnuplot_mouse.js
/usr/share/gnuplot/gnuplot/6.0/js/canvasmath.js
/usr/share/gnuplot/gnuplot/6.0/js/gnuplot_mouse.css
/usr/share/gnuplot/gnuplot/6.0/js/README
/usr/share/gnuplot/gnuplot/6.0/js/gnuplot_svg_2018.js
/usr/share/gnuplot/gnuplot/6.0/js/previouszoom.png
/usr/share/gnuplot/gnuplot/6.0/js/grid.png
/usr/share/gnuplot/gnuplot/6.0/js/nextzoom.png
/usr/share/gnuplot/gnuplot/6.0/js/gnuplot_common.js
/usr/share/gnuplot/gnuplot/6.0/js/canvastext.js
/usr/share/gnuplot/gnuplot/6.0/js/gnuplot_dashedlines.js
/usr/share/gnuplot/gnuplot/6.0/js/textzoom.png
/usr/share/gnuplot/gnuplot/6.0/js/help.png
/usr/share/gnuplot/gnuplot/6.0/js/gnuplot_svg.js
/usr/bin
/usr/bin/gnuplot
/usr/libexec/gnuplot/6.0
/usr/libexec/gnuplot/6.0/gnuplot_x11
/usr/man/man1
/usr/man/man1/gnuplot.1
/usr/man/ja/man1
/usr/man/ja/man1/gnuplot.1
