28+16
/opt
/opt/jdk
/opt/jdk-28+16
/opt/jdk-28+16/conf
/opt/jdk-28+16/conf/jaxp-strict.properties.template
/opt/jdk-28+16/conf/jaxp.properties
/opt/jdk-28+16/conf/net.properties
/opt/jdk-28+16/conf/security
/opt/jdk-28+16/conf/security/policy
/opt/jdk-28+16/conf/security/policy/limited
/opt/jdk-28+16/conf/security/policy/limited/default_local.policy
/opt/jdk-28+16/conf/security/policy/limited/exempt_local.policy
/opt/jdk-28+16/conf/security/policy/limited/default_US_export.policy
/opt/jdk-28+16/conf/security/policy/unlimited
/opt/jdk-28+16/conf/security/policy/unlimited/default_local.policy
/opt/jdk-28+16/conf/security/policy/unlimited/default_US_export.policy
/opt/jdk-28+16/conf/security/policy/README.txt
/opt/jdk-28+16/conf/security/java.security
/opt/jdk-28+16/conf/management
/opt/jdk-28+16/conf/management/jmxremote.password.template
/opt/jdk-28+16/conf/management/jmxremote.access
/opt/jdk-28+16/conf/management/management.properties
/opt/jdk-28+16/conf/sound.properties
/opt/jdk-28+16/conf/logging.properties
/opt/jdk-28+16/conf/bash-completion
/opt/jdk-28+16/conf/bash-completion/jcmd
/opt/jdk-28+16/lib
/opt/jdk-28+16/lib/libjli.so
/opt/jdk-28+16/lib/jexec
/opt/jdk-28+16/lib/libdt_socket.so
/opt/jdk-28+16/lib/jfr
/opt/jdk-28+16/lib/jfr/default.jfc
/opt/jdk-28+16/lib/jfr/profile.jfc
/opt/jdk-28+16/lib/libextnet.so
/opt/jdk-28+16/lib/libjawt.so
/opt/jdk-28+16/lib/libsimdsort.so
/opt/jdk-28+16/lib/libmlib_image.so
/opt/jdk-28+16/lib/security
/opt/jdk-28+16/lib/security/cacerts
/opt/jdk-28+16/lib/security/blocked.certs
/opt/jdk-28+16/lib/security/public_suffix_list.dat
/opt/jdk-28+16/lib/libj2pkcs11.so
/opt/jdk-28+16/lib/libjsvml.so
/opt/jdk-28+16/lib/classlist
/opt/jdk-28+16/lib/tzdb.dat
/opt/jdk-28+16/lib/psfont.properties.ja
/opt/jdk-28+16/lib/libj2pcsc.so
/opt/jdk-28+16/lib/libjsound.so
/opt/jdk-28+16/lib/libprefs.so
/opt/jdk-28+16/lib/libjsig.so
/opt/jdk-28+16/lib/libmanagement_agent.so
/opt/jdk-28+16/lib/libattach.so
/opt/jdk-28+16/lib/libsyslookup.so
/opt/jdk-28+16/lib/libzip.so
/opt/jdk-28+16/lib/libawt_xawt.so
/opt/jdk-28+16/lib/src.zip
/opt/jdk-28+16/lib/liblcms.so
/opt/jdk-28+16/lib/jspawnhelper
/opt/jdk-28+16/lib/libsaproc.so
/opt/jdk-28+16/lib/libnet.so
/opt/jdk-28+16/lib/librmi.so
/opt/jdk-28+16/lib/psfontj2d.properties
/opt/jdk-28+16/lib/libverify.so
/opt/jdk-28+16/lib/libawt_headless.so
/opt/jdk-28+16/lib/libmanagement.so
/opt/jdk-28+16/lib/server
/opt/jdk-28+16/lib/server/classes_nocoh.jsa
/opt/jdk-28+16/lib/server/classes_nocoops_nocoh.jsa
/opt/jdk-28+16/lib/server/classes_nocoops_preview.jsa
/opt/jdk-28+16/lib/server/classes_nocoops_nocoh_preview.jsa
/opt/jdk-28+16/lib/server/libjsig.so
/opt/jdk-28+16/lib/server/classes_preview.jsa
/opt/jdk-28+16/lib/server/classes_nocoops.jsa
/opt/jdk-28+16/lib/server/libjvm.so
/opt/jdk-28+16/lib/server/classes.jsa
/opt/jdk-28+16/lib/server/classes_nocoh_preview.jsa
/opt/jdk-28+16/lib/libnio.so
/opt/jdk-28+16/lib/libj2gss.so
/opt/jdk-28+16/lib/jrt-fs.jar
/opt/jdk-28+16/lib/libawt.so
/opt/jdk-28+16/lib/jvm.cfg
/opt/jdk-28+16/lib/modules
/opt/jdk-28+16/lib/ct.sym
/opt/jdk-28+16/lib/libinstrument.so
/opt/jdk-28+16/lib/libfontmanager.so
/opt/jdk-28+16/lib/libmanagement_ext.so
/opt/jdk-28+16/lib/libjdwp.so
/opt/jdk-28+16/lib/libjimage.so
/opt/jdk-28+16/lib/libsctp.so
/opt/jdk-28+16/lib/libsplashscreen.so
/opt/jdk-28+16/lib/libjavajpeg.so
/opt/jdk-28+16/lib/libjava.so
/opt/jdk-28+16/bin
/opt/jdk-28+16/bin/jmod
/opt/jdk-28+16/bin/jinfo
/opt/jdk-28+16/bin/jfr
/opt/jdk-28+16/bin/jwebserver
/opt/jdk-28+16/bin/jnativescan
/opt/jdk-28+16/bin/keytool
/opt/jdk-28+16/bin/jdeprscan
/opt/jdk-28+16/bin/jdeps
/opt/jdk-28+16/bin/jcmd
/opt/jdk-28+16/bin/jstack
/opt/jdk-28+16/bin/jshell
/opt/jdk-28+16/bin/jpackage
/opt/jdk-28+16/bin/jmap
/opt/jdk-28+16/bin/serialver
/opt/jdk-28+16/bin/jstat
/opt/jdk-28+16/bin/jhsdb
/opt/jdk-28+16/bin/javap
/opt/jdk-28+16/bin/jar
/opt/jdk-28+16/bin/javac
/opt/jdk-28+16/bin/rmiregistry
/opt/jdk-28+16/bin/jlink
/opt/jdk-28+16/bin/java
/opt/jdk-28+16/bin/jdb
/opt/jdk-28+16/bin/jconsole
/opt/jdk-28+16/bin/jstatd
/opt/jdk-28+16/bin/jarsigner
/opt/jdk-28+16/bin/jps
/opt/jdk-28+16/bin/javadoc
/opt/jdk-28+16/bin/jimage
/opt/jdk-28+16/release
/opt/jdk-28+16/jmods
/opt/jdk-28+16/jmods/jdk.unsupported.desktop.jmod
/opt/jdk-28+16/jmods/jdk.jdeps.jmod
/opt/jdk-28+16/jmods/java.prefs.jmod
/opt/jdk-28+16/jmods/jdk.jconsole.jmod
/opt/jdk-28+16/jmods/java.compiler.jmod
/opt/jdk-28+16/jmods/jdk.crypto.ec.jmod
/opt/jdk-28+16/jmods/java.management.rmi.jmod
/opt/jdk-28+16/jmods/jdk.management.jfr.jmod
/opt/jdk-28+16/jmods/java.security.sasl.jmod
/opt/jdk-28+16/jmods/java.instrument.jmod
/opt/jdk-28+16/jmods/jdk.management.jmod
/opt/jdk-28+16/jmods/jdk.management.agent.jmod
/opt/jdk-28+16/jmods/java.smartcardio.jmod
/opt/jdk-28+16/jmods/jdk.internal.jvmstat.jmod
/opt/jdk-28+16/jmods/jdk.internal.le.jmod
/opt/jdk-28+16/jmods/jdk.editpad.jmod
/opt/jdk-28+16/jmods/jdk.incubator.vector.jmod
/opt/jdk-28+16/jmods/jdk.javadoc.jmod
/opt/jdk-28+16/jmods/jdk.jpackage.jmod
/opt/jdk-28+16/jmods/java.sql.rowset.jmod
/opt/jdk-28+16/jmods/jdk.security.jgss.jmod
/opt/jdk-28+16/jmods/jdk.unsupported.jmod
/opt/jdk-28+16/jmods/jdk.internal.opt.jmod
/opt/jdk-28+16/jmods/jdk.httpserver.jmod
/opt/jdk-28+16/jmods/jdk.charsets.jmod
/opt/jdk-28+16/jmods/jdk.compiler.jmod
/opt/jdk-28+16/jmods/jdk.naming.rmi.jmod
/opt/jdk-28+16/jmods/jdk.jstatd.jmod
/opt/jdk-28+16/jmods/jdk.localedata.jmod
/opt/jdk-28+16/jmods/jdk.jshell.jmod
/opt/jdk-28+16/jmods/java.base.jmod
/opt/jdk-28+16/jmods/jdk.jfr.jmod
/opt/jdk-28+16/jmods/jdk.dynalink.jmod
/opt/jdk-28+16/jmods/java.logging.jmod
/opt/jdk-28+16/jmods/jdk.jdwp.agent.jmod
/opt/jdk-28+16/jmods/java.naming.jmod
/opt/jdk-28+16/jmods/java.xml.crypto.jmod
/opt/jdk-28+16/jmods/java.security.jgss.jmod
/opt/jdk-28+16/jmods/jdk.jlink.jmod
/opt/jdk-28+16/jmods/java.scripting.jmod
/opt/jdk-28+16/jmods/jdk.jdi.jmod
/opt/jdk-28+16/jmods/jdk.security.auth.jmod
/opt/jdk-28+16/jmods/java.datatransfer.jmod
/opt/jdk-28+16/jmods/jdk.naming.dns.jmod
/opt/jdk-28+16/jmods/jdk.jartool.jmod
/opt/jdk-28+16/jmods/java.net.http.jmod
/opt/jdk-28+16/jmods/jdk.incubator.json.jmod
/opt/jdk-28+16/jmods/jdk.crypto.cryptoki.jmod
/opt/jdk-28+16/jmods/jdk.xml.dom.jmod
/opt/jdk-28+16/jmods/jdk.accessibility.jmod
/opt/jdk-28+16/jmods/jdk.nio.mapmode.jmod
/opt/jdk-28+16/jmods/jdk.internal.ed.jmod
/opt/jdk-28+16/jmods/java.transaction.xa.jmod
/opt/jdk-28+16/jmods/java.management.jmod
/opt/jdk-28+16/jmods/java.xml.jmod
/opt/jdk-28+16/jmods/jdk.zipfs.jmod
/opt/jdk-28+16/jmods/java.rmi.jmod
/opt/jdk-28+16/jmods/java.sql.jmod
/opt/jdk-28+16/jmods/jdk.internal.md.jmod
/opt/jdk-28+16/jmods/jdk.attach.jmod
/opt/jdk-28+16/jmods/jdk.sctp.jmod
/opt/jdk-28+16/jmods/java.se.jmod
/opt/jdk-28+16/jmods/jdk.jcmd.jmod
/opt/jdk-28+16/jmods/jdk.net.jmod
/opt/jdk-28+16/jmods/jdk.hotspot.agent.jmod
/opt/jdk-28+16/jmods/java.desktop.jmod
/opt/jdk-28+16/man
/opt/jdk-28+16/man/man1
/opt/jdk-28+16/man/man1/jar.1
/opt/jdk-28+16/man/man1/jlink.1
/opt/jdk-28+16/man/man1/jarsigner.1
/opt/jdk-28+16/man/man1/jconsole.1
/opt/jdk-28+16/man/man1/jdeps.1
/opt/jdk-28+16/man/man1/jinfo.1
/opt/jdk-28+16/man/man1/jdeprscan.1
/opt/jdk-28+16/man/man1/jmod.1
/opt/jdk-28+16/man/man1/keytool.1
/opt/jdk-28+16/man/man1/jhsdb.1
/opt/jdk-28+16/man/man1/jwebserver.1
/opt/jdk-28+16/man/man1/jps.1
/opt/jdk-28+16/man/man1/javac.1
/opt/jdk-28+16/man/man1/jmap.1
/opt/jdk-28+16/man/man1/serialver.1
/opt/jdk-28+16/man/man1/javadoc.1
/opt/jdk-28+16/man/man1/javap.1
/opt/jdk-28+16/man/man1/java.1
/opt/jdk-28+16/man/man1/jnativescan.1
/opt/jdk-28+16/man/man1/jstatd.1
/opt/jdk-28+16/man/man1/jpackage.1
/opt/jdk-28+16/man/man1/jdb.1
/opt/jdk-28+16/man/man1/jcmd.1
/opt/jdk-28+16/man/man1/jstat.1
/opt/jdk-28+16/man/man1/jstack.1
/opt/jdk-28+16/man/man1/jshell.1
/opt/jdk-28+16/man/man1/jfr.1
/opt/jdk-28+16/man/man1/rmiregistry.1
/opt/jdk-28+16/include
/opt/jdk-28+16/include/jawt.h
/opt/jdk-28+16/include/linux
/opt/jdk-28+16/include/linux/jni_md.h
/opt/jdk-28+16/include/linux/jawt_md.h
/opt/jdk-28+16/include/jvmti.h
/opt/jdk-28+16/include/jdwpTransport.h
/opt/jdk-28+16/include/jvmticmlr.h
/opt/jdk-28+16/include/jni.h
/opt/jdk-28+16/include/classfile_constants.h
/opt/jdk-28+16/legal
/opt/jdk-28+16/legal/jdk.javadoc
/opt/jdk-28+16/legal/jdk.javadoc/highlightjs.md
/opt/jdk-28+16/legal/jdk.javadoc/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.javadoc/dejavufonts.md
/opt/jdk-28+16/legal/jdk.javadoc/LICENSE
/opt/jdk-28+16/legal/jdk.javadoc/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.localedata
/opt/jdk-28+16/legal/jdk.localedata/thaidict.md
/opt/jdk-28+16/legal/jdk.localedata/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.localedata/LICENSE
/opt/jdk-28+16/legal/jdk.localedata/cldr.md
/opt/jdk-28+16/legal/jdk.localedata/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.security.jgss
/opt/jdk-28+16/legal/jdk.security.jgss/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.security.jgss/LICENSE
/opt/jdk-28+16/legal/jdk.security.jgss/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.management.jfr
/opt/jdk-28+16/legal/jdk.management.jfr/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.management.jfr/LICENSE
/opt/jdk-28+16/legal/jdk.management.jfr/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.base
/opt/jdk-28+16/legal/java.base/gcc.md
/opt/jdk-28+16/legal/java.base/siphash.md
/opt/jdk-28+16/legal/java.base/c-libutl.md
/opt/jdk-28+16/legal/java.base/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.base/icu.md
/opt/jdk-28+16/legal/java.base/unicode.md
/opt/jdk-28+16/legal/java.base/LICENSE
/opt/jdk-28+16/legal/java.base/public_suffix.md
/opt/jdk-28+16/legal/java.base/cldr.md
/opt/jdk-28+16/legal/java.base/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.rmi
/opt/jdk-28+16/legal/java.rmi/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.rmi/LICENSE
/opt/jdk-28+16/legal/java.rmi/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.jconsole
/opt/jdk-28+16/legal/jdk.jconsole/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.jconsole/LICENSE
/opt/jdk-28+16/legal/jdk.jconsole/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.scripting
/opt/jdk-28+16/legal/java.scripting/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.scripting/LICENSE
/opt/jdk-28+16/legal/java.scripting/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.naming.rmi
/opt/jdk-28+16/legal/jdk.naming.rmi/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.naming.rmi/LICENSE
/opt/jdk-28+16/legal/jdk.naming.rmi/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.unsupported
/opt/jdk-28+16/legal/jdk.unsupported/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.unsupported/LICENSE
/opt/jdk-28+16/legal/jdk.unsupported/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.prefs
/opt/jdk-28+16/legal/java.prefs/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.prefs/LICENSE
/opt/jdk-28+16/legal/java.prefs/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.desktop
/opt/jdk-28+16/legal/java.desktop/giflib.md
/opt/jdk-28+16/legal/java.desktop/pipewire.md
/opt/jdk-28+16/legal/java.desktop/mesa3d.md
/opt/jdk-28+16/legal/java.desktop/harfbuzz.md
/opt/jdk-28+16/legal/java.desktop/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.desktop/jpeg.md
/opt/jdk-28+16/legal/java.desktop/xwd.md
/opt/jdk-28+16/legal/java.desktop/LICENSE
/opt/jdk-28+16/legal/java.desktop/colorimaging.md
/opt/jdk-28+16/legal/java.desktop/lcms.md
/opt/jdk-28+16/legal/java.desktop/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.desktop/libpng.md
/opt/jdk-28+16/legal/jdk.crypto.ec
/opt/jdk-28+16/legal/jdk.crypto.ec/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.crypto.ec/LICENSE
/opt/jdk-28+16/legal/jdk.crypto.ec/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.logging
/opt/jdk-28+16/legal/java.logging/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.logging/LICENSE
/opt/jdk-28+16/legal/java.logging/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.incubator.vector
/opt/jdk-28+16/legal/jdk.incubator.vector/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.incubator.vector/LICENSE
/opt/jdk-28+16/legal/jdk.incubator.vector/sleef.md
/opt/jdk-28+16/legal/jdk.incubator.vector/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.httpserver
/opt/jdk-28+16/legal/jdk.httpserver/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.httpserver/LICENSE
/opt/jdk-28+16/legal/jdk.httpserver/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.management
/opt/jdk-28+16/legal/java.management/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.management/LICENSE
/opt/jdk-28+16/legal/java.management/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.zipfs
/opt/jdk-28+16/legal/jdk.zipfs/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.zipfs/LICENSE
/opt/jdk-28+16/legal/jdk.zipfs/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.internal.ed
/opt/jdk-28+16/legal/jdk.internal.ed/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.internal.ed/LICENSE
/opt/jdk-28+16/legal/jdk.internal.ed/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.net
/opt/jdk-28+16/legal/jdk.net/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.net/LICENSE
/opt/jdk-28+16/legal/jdk.net/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.jdeps
/opt/jdk-28+16/legal/jdk.jdeps/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.jdeps/LICENSE
/opt/jdk-28+16/legal/jdk.jdeps/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.compiler
/opt/jdk-28+16/legal/jdk.compiler/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.compiler/LICENSE
/opt/jdk-28+16/legal/jdk.compiler/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.compiler
/opt/jdk-28+16/legal/java.compiler/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.compiler/LICENSE
/opt/jdk-28+16/legal/java.compiler/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.transaction.xa
/opt/jdk-28+16/legal/java.transaction.xa/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.transaction.xa/LICENSE
/opt/jdk-28+16/legal/java.transaction.xa/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.instrument
/opt/jdk-28+16/legal/java.instrument/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.instrument/LICENSE
/opt/jdk-28+16/legal/java.instrument/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.internal.opt
/opt/jdk-28+16/legal/jdk.internal.opt/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.internal.opt/LICENSE
/opt/jdk-28+16/legal/jdk.internal.opt/jopt-simple.md
/opt/jdk-28+16/legal/jdk.internal.opt/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.jshell
/opt/jdk-28+16/legal/jdk.jshell/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.jshell/LICENSE
/opt/jdk-28+16/legal/jdk.jshell/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.jartool
/opt/jdk-28+16/legal/jdk.jartool/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.jartool/LICENSE
/opt/jdk-28+16/legal/jdk.jartool/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.jstatd
/opt/jdk-28+16/legal/jdk.jstatd/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.jstatd/LICENSE
/opt/jdk-28+16/legal/jdk.jstatd/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.dynalink
/opt/jdk-28+16/legal/jdk.dynalink/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.dynalink/LICENSE
/opt/jdk-28+16/legal/jdk.dynalink/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.dynalink/dynalink.md
/opt/jdk-28+16/legal/jdk.jdwp.agent
/opt/jdk-28+16/legal/jdk.jdwp.agent/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.jdwp.agent/LICENSE
/opt/jdk-28+16/legal/jdk.jdwp.agent/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.management
/opt/jdk-28+16/legal/jdk.management/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.management/LICENSE
/opt/jdk-28+16/legal/jdk.management/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.security.jgss
/opt/jdk-28+16/legal/java.security.jgss/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.security.jgss/LICENSE
/opt/jdk-28+16/legal/java.security.jgss/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.unsupported.desktop
/opt/jdk-28+16/legal/jdk.unsupported.desktop/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.unsupported.desktop/LICENSE
/opt/jdk-28+16/legal/jdk.unsupported.desktop/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.attach
/opt/jdk-28+16/legal/jdk.attach/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.attach/LICENSE
/opt/jdk-28+16/legal/jdk.attach/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.security.sasl
/opt/jdk-28+16/legal/java.security.sasl/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.security.sasl/LICENSE
/opt/jdk-28+16/legal/java.security.sasl/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.accessibility
/opt/jdk-28+16/legal/jdk.accessibility/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.accessibility/LICENSE
/opt/jdk-28+16/legal/jdk.accessibility/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.smartcardio
/opt/jdk-28+16/legal/java.smartcardio/pcsclite.md
/opt/jdk-28+16/legal/java.smartcardio/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.smartcardio/LICENSE
/opt/jdk-28+16/legal/java.smartcardio/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.sql.rowset
/opt/jdk-28+16/legal/java.sql.rowset/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.sql.rowset/LICENSE
/opt/jdk-28+16/legal/java.sql.rowset/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.jpackage
/opt/jdk-28+16/legal/jdk.jpackage/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.jpackage/LICENSE
/opt/jdk-28+16/legal/jdk.jpackage/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.jdi
/opt/jdk-28+16/legal/jdk.jdi/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.jdi/LICENSE
/opt/jdk-28+16/legal/jdk.jdi/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.sql
/opt/jdk-28+16/legal/java.sql/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.sql/LICENSE
/opt/jdk-28+16/legal/java.sql/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.internal.md
/opt/jdk-28+16/legal/jdk.internal.md/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.internal.md/LICENSE
/opt/jdk-28+16/legal/jdk.internal.md/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.internal.md/commonmark.md
/opt/jdk-28+16/legal/java.xml
/opt/jdk-28+16/legal/java.xml/dom.md
/opt/jdk-28+16/legal/java.xml/bcel.md
/opt/jdk-28+16/legal/java.xml/xerces.md
/opt/jdk-28+16/legal/java.xml/schema10part2.md
/opt/jdk-28+16/legal/java.xml/xmlxsd.md
/opt/jdk-28+16/legal/java.xml/xalan.md
/opt/jdk-28+16/legal/java.xml/xhtml10.md
/opt/jdk-28+16/legal/java.xml/xhtml11.md
/opt/jdk-28+16/legal/java.xml/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.xml/xhtml10schema.md
/opt/jdk-28+16/legal/java.xml/jcup.md
/opt/jdk-28+16/legal/java.xml/LICENSE
/opt/jdk-28+16/legal/java.xml/schema10part1.md
/opt/jdk-28+16/legal/java.xml/xhtml11schema.md
/opt/jdk-28+16/legal/java.xml/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.xml/xmlspec.md
/opt/jdk-28+16/legal/jdk.incubator.json
/opt/jdk-28+16/legal/jdk.incubator.json/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.incubator.json/LICENSE
/opt/jdk-28+16/legal/jdk.incubator.json/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.jlink
/opt/jdk-28+16/legal/jdk.jlink/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.jlink/LICENSE
/opt/jdk-28+16/legal/jdk.jlink/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.se
/opt/jdk-28+16/legal/java.se/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.se/LICENSE
/opt/jdk-28+16/legal/java.se/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.internal.le
/opt/jdk-28+16/legal/jdk.internal.le/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.internal.le/jline.md
/opt/jdk-28+16/legal/jdk.internal.le/LICENSE
/opt/jdk-28+16/legal/jdk.internal.le/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.crypto.cryptoki
/opt/jdk-28+16/legal/jdk.crypto.cryptoki/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.crypto.cryptoki/pkcs11cryptotoken.md
/opt/jdk-28+16/legal/jdk.crypto.cryptoki/pkcs11wrapper.md
/opt/jdk-28+16/legal/jdk.crypto.cryptoki/LICENSE
/opt/jdk-28+16/legal/jdk.crypto.cryptoki/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.jcmd
/opt/jdk-28+16/legal/jdk.jcmd/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.jcmd/LICENSE
/opt/jdk-28+16/legal/jdk.jcmd/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.naming
/opt/jdk-28+16/legal/java.naming/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.naming/LICENSE
/opt/jdk-28+16/legal/java.naming/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.naming.dns
/opt/jdk-28+16/legal/jdk.naming.dns/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.naming.dns/LICENSE
/opt/jdk-28+16/legal/jdk.naming.dns/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.internal.jvmstat
/opt/jdk-28+16/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.internal.jvmstat/LICENSE
/opt/jdk-28+16/legal/jdk.internal.jvmstat/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.editpad
/opt/jdk-28+16/legal/jdk.editpad/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.editpad/LICENSE
/opt/jdk-28+16/legal/jdk.editpad/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.jfr
/opt/jdk-28+16/legal/jdk.jfr/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.jfr/LICENSE
/opt/jdk-28+16/legal/jdk.jfr/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.nio.mapmode
/opt/jdk-28+16/legal/jdk.nio.mapmode/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.nio.mapmode/LICENSE
/opt/jdk-28+16/legal/jdk.nio.mapmode/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.management.agent
/opt/jdk-28+16/legal/jdk.management.agent/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.management.agent/LICENSE
/opt/jdk-28+16/legal/jdk.management.agent/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.hotspot.agent
/opt/jdk-28+16/legal/jdk.hotspot.agent/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.hotspot.agent/LICENSE
/opt/jdk-28+16/legal/jdk.hotspot.agent/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.xml.crypto
/opt/jdk-28+16/legal/java.xml.crypto/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.xml.crypto/santuario.md
/opt/jdk-28+16/legal/java.xml.crypto/LICENSE
/opt/jdk-28+16/legal/java.xml.crypto/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.charsets
/opt/jdk-28+16/legal/jdk.charsets/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.charsets/LICENSE
/opt/jdk-28+16/legal/jdk.charsets/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.net.http
/opt/jdk-28+16/legal/java.net.http/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.net.http/LICENSE
/opt/jdk-28+16/legal/java.net.http/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.sctp
/opt/jdk-28+16/legal/jdk.sctp/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.sctp/LICENSE
/opt/jdk-28+16/legal/jdk.sctp/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.datatransfer
/opt/jdk-28+16/legal/java.datatransfer/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.datatransfer/LICENSE
/opt/jdk-28+16/legal/java.datatransfer/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.security.auth
/opt/jdk-28+16/legal/jdk.security.auth/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.security.auth/LICENSE
/opt/jdk-28+16/legal/jdk.security.auth/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/jdk.xml.dom
/opt/jdk-28+16/legal/jdk.xml.dom/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/jdk.xml.dom/LICENSE
/opt/jdk-28+16/legal/jdk.xml.dom/ASSEMBLY_EXCEPTION
/opt/jdk-28+16/legal/java.management.rmi
/opt/jdk-28+16/legal/java.management.rmi/ADDITIONAL_LICENSE_INFO
/opt/jdk-28+16/legal/java.management.rmi/LICENSE
/opt/jdk-28+16/legal/java.management.rmi/ASSEMBLY_EXCEPTION
