5.5.1
/usr/lib
/usr/lib/liblua.so.5.5
/usr/lib/liblua.so.5.5.1
/usr/lib/pkgconfig
/usr/lib/pkgconfig/lua.pc
/usr/lib/liblua.so
/usr/share/doc/lua-5.5.1/lua.css
/usr/share/doc/lua-5.5.1/OSIApproved.png
/usr/share/doc/lua-5.5.1/manual.css
/usr/share/doc/lua-5.5.1/manual.html
/usr/share/doc/lua-5.5.1/contents.html
/usr/share/doc/lua-5.5.1/readme.html
/usr/share/doc/lua-5.5.1/logo.png
/usr/share/doc/lua-5.5.1/index.css
/usr/share/man/man1/luac.1
/usr/share/man/man1/lua.1
/usr/bin
/usr/bin/luac
/usr/bin/lua
/usr/include/lualib.h
/usr/include/lua.hpp
/usr/include/lauxlib.h
/usr/include/lua.h
/usr/include/luaconf.h
