4.6.1
/usr/lib/pkgconfig/libR.pc
/usr/lib/R
/usr/lib/R/COPYING
/usr/lib/R/lib/libR.so
/usr/lib/R/share/bibliographies
/usr/lib/R/share/bibliographies/utils.R
/usr/lib/R/share/bibliographies/parallel.R
/usr/lib/R/share/bibliographies/grid.R
/usr/lib/R/share/bibliographies/grDevices.R
/usr/lib/R/share/bibliographies/methods.R
/usr/lib/R/share/bibliographies/R.rds
/usr/lib/R/share/bibliographies/stats.R
/usr/lib/R/share/bibliographies/datasets.R
/usr/lib/R/share/bibliographies/graphics.R
/usr/lib/R/share/bibliographies/base.R
/usr/lib/R/share/bibliographies/splines.R
/usr/lib/R/share/sh
/usr/lib/R/share/sh/echo.sh
/usr/lib/R/share/R
/usr/lib/R/share/R/examples-footer.R
/usr/lib/R/share/R/nspackloader.R
/usr/lib/R/share/R/examples-header.R
/usr/lib/R/share/R/REMOVE.R
/usr/lib/R/share/R/tests-startup.R
/usr/lib/R/share/licenses
/usr/lib/R/share/licenses/CC0-1.0
/usr/lib/R/share/licenses/BSD_3_clause
/usr/lib/R/share/licenses/LGPL-3
/usr/lib/R/share/licenses/LGPL-2.1
/usr/lib/R/share/licenses/Artistic-2.0
/usr/lib/R/share/licenses/AGPL-3
/usr/lib/R/share/licenses/MIT
/usr/lib/R/share/licenses/GPL-2
/usr/lib/R/share/licenses/LGPL-2
/usr/lib/R/share/licenses/license.db
/usr/lib/R/share/licenses/Apache-2.0
/usr/lib/R/share/licenses/BSD_2_clause
/usr/lib/R/share/licenses/GPL-3
/usr/lib/R/share/texmf/tex/latex
/usr/lib/R/share/texmf/tex/latex/jss.cls
/usr/lib/R/share/texmf/tex/latex/Sweave.sty
/usr/lib/R/share/texmf/tex/latex/Rd.sty
/usr/lib/R/share/texmf/tex/latex/omscmtt.fd
/usr/lib/R/share/texmf/bibtex/bib
/usr/lib/R/share/texmf/bibtex/bib/RJournal.bib
/usr/lib/R/share/texmf/bibtex/bib/Rnews.bib
/usr/lib/R/share/texmf/bibtex/bst
/usr/lib/R/share/texmf/bibtex/bst/jss.bst
/usr/lib/R/share/dictionaries
/usr/lib/R/share/dictionaries/R_manuals.rds
/usr/lib/R/share/dictionaries/R_vignettes.rds
/usr/lib/R/share/dictionaries/R_Rd_files.rds
/usr/lib/R/share/dictionaries/en_stats.txt
/usr/lib/R/share/dictionaries/R_Rd_files.txt
/usr/lib/R/share/dictionaries/en_stats.rds
/usr/lib/R/share/dictionaries/R_manuals.txt
/usr/lib/R/share/dictionaries/R_vignettes.txt
/usr/lib/R/share/make
/usr/lib/R/share/make/config.mk
/usr/lib/R/share/make/winshlib.mk
/usr/lib/R/share/make/check_vars_ini.mk
/usr/lib/R/share/make/lazycomp.mk
/usr/lib/R/share/make/check_vars_out.mk
/usr/lib/R/share/make/vars.mk
/usr/lib/R/share/make/shlib.mk
/usr/lib/R/share/make/clean.mk
/usr/lib/R/share/make/basepkg.mk
/usr/lib/R/share/java
/usr/lib/R/share/java/README
/usr/lib/R/share/java/getsp.class
/usr/lib/R/share/encodings
/usr/lib/R/share/encodings/character-sets
/usr/lib/R/share/encodings/Adobe-glyphlist
/usr/lib/R/bin
/usr/lib/R/bin/exec
/usr/lib/R/bin/exec/R
/usr/lib/R/bin/pager
/usr/lib/R/bin/rtags
/usr/lib/R/bin/mkinstalldirs
/usr/lib/R/bin/R
/usr/lib/R/bin/Rcmd
/usr/lib/R/bin/Rscript
/usr/lib/R/bin/javareconf
/usr/lib/R/bin/libtool
/usr/lib/R/etc
/usr/lib/R/etc/ldpaths
/usr/lib/R/etc/repositories
/usr/lib/R/etc/Makeconf
/usr/lib/R/etc/javaconf
/usr/lib/R/etc/Renviron
/usr/lib/R/modules/R_de.so
/usr/lib/R/modules/lapack.so
/usr/lib/R/modules/R_X11.so
/usr/lib/R/modules/internet.so
/usr/lib/R/library/stats/doc/reshape.pdf
/usr/lib/R/library/stats/INDEX
/usr/lib/R/library/stats/SOURCES.ts
/usr/lib/R/library/stats/COPYRIGHTS.modreg
/usr/lib/R/library/stats/html/R.css
/usr/lib/R/library/stats/html/00Index.html
/usr/lib/R/library/stats/R/stats.rdx
/usr/lib/R/library/stats/R/stats
/usr/lib/R/library/stats/R/stats.rdb
/usr/lib/R/library/stats/DESCRIPTION
/usr/lib/R/library/stats/libs/stats.so
/usr/lib/R/library/stats/help/stats.rdx
/usr/lib/R/library/stats/help/aliases.rds
/usr/lib/R/library/stats/help/AnIndex
/usr/lib/R/library/stats/help/stats.rdb
/usr/lib/R/library/stats/help/paths.rds
/usr/lib/R/library/stats/Meta/Rd.rds
/usr/lib/R/library/stats/Meta/links.rds
/usr/lib/R/library/stats/Meta/features.rds
/usr/lib/R/library/stats/Meta/package.rds
/usr/lib/R/library/stats/Meta/hsearch.rds
/usr/lib/R/library/stats/Meta/nsInfo.rds
/usr/lib/R/library/stats/Meta/demo.rds
/usr/lib/R/library/stats/NAMESPACE
/usr/lib/R/library/stats/demo/lm.glm.R
/usr/lib/R/library/stats/demo/smooth.R
/usr/lib/R/library/stats/demo/nlm.R
/usr/lib/R/library/stats/demo/glm.vr.R
/usr/lib/R/library/graphics/INDEX
/usr/lib/R/library/graphics/html/R.css
/usr/lib/R/library/graphics/html/00Index.html
/usr/lib/R/library/graphics/R/graphics
/usr/lib/R/library/graphics/R/graphics.rdx
/usr/lib/R/library/graphics/R/graphics.rdb
/usr/lib/R/library/graphics/DESCRIPTION
/usr/lib/R/library/graphics/libs/graphics.so
/usr/lib/R/library/graphics/help/aliases.rds
/usr/lib/R/library/graphics/help/graphics.rdx
/usr/lib/R/library/graphics/help/AnIndex
/usr/lib/R/library/graphics/help/figures/pch.pdf
/usr/lib/R/library/graphics/help/figures/pch.svg
/usr/lib/R/library/graphics/help/figures/mai.pdf
/usr/lib/R/library/graphics/help/figures/oma.pdf
/usr/lib/R/library/graphics/help/figures/oma.png
/usr/lib/R/library/graphics/help/figures/mai.png
/usr/lib/R/library/graphics/help/figures/pch.png
/usr/lib/R/library/graphics/help/paths.rds
/usr/lib/R/library/graphics/help/graphics.rdb
/usr/lib/R/library/graphics/Meta/Rd.rds
/usr/lib/R/library/graphics/Meta/links.rds
/usr/lib/R/library/graphics/Meta/features.rds
/usr/lib/R/library/graphics/Meta/package.rds
/usr/lib/R/library/graphics/Meta/hsearch.rds
/usr/lib/R/library/graphics/Meta/nsInfo.rds
/usr/lib/R/library/graphics/Meta/demo.rds
/usr/lib/R/library/graphics/NAMESPACE
/usr/lib/R/library/graphics/demo/Japanese.R
/usr/lib/R/library/graphics/demo/image.R
/usr/lib/R/library/graphics/demo/plotmath.R
/usr/lib/R/library/graphics/demo/Hershey.R
/usr/lib/R/library/graphics/demo/persp.R
/usr/lib/R/library/graphics/demo/graphics.R
/usr/lib/R/library/Matrix/doc/Introduction.R
/usr/lib/R/library/Matrix/doc/Intro2Matrix.pdf
/usr/lib/R/library/Matrix/doc/Comparisons.R
/usr/lib/R/library/Matrix/doc/sparseModels.Rnw
/usr/lib/R/library/Matrix/doc/Design-issues.Rnw
/usr/lib/R/library/Matrix/doc/Comparisons.pdf
/usr/lib/R/library/Matrix/doc/Introduction.pdf
/usr/lib/R/library/Matrix/doc/SuiteSparse/LICENSE.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/COLAMD/Doc/License.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/COLAMD/Doc/ChangeLog
/usr/lib/R/library/Matrix/doc/SuiteSparse/COLAMD/README.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/CCOLAMD/Doc/License.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/CCOLAMD/Doc/ChangeLog
/usr/lib/R/library/Matrix/doc/SuiteSparse/CCOLAMD/README.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/CHOLMOD/Doc/License.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/CHOLMOD/Doc/ChangeLog
/usr/lib/R/library/Matrix/doc/SuiteSparse/CHOLMOD/SuiteSparse_metis/LICENSE.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/CHOLMOD/SuiteSparse_metis/Changelog
/usr/lib/R/library/Matrix/doc/SuiteSparse/CHOLMOD/SuiteSparse_metis/README.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/CHOLMOD/README.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/ChangeLog
/usr/lib/R/library/Matrix/doc/SuiteSparse/SuiteSparse_config/README.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/CAMD/Doc/License.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/CAMD/Doc/ChangeLog
/usr/lib/R/library/Matrix/doc/SuiteSparse/CAMD/README.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/CXSparse/Doc/License.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/CXSparse/Doc/ChangeLog
/usr/lib/R/library/Matrix/doc/SuiteSparse/CXSparse/README.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/AMD/Doc/License.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/AMD/Doc/ChangeLog
/usr/lib/R/library/Matrix/doc/SuiteSparse/AMD/README.txt
/usr/lib/R/library/Matrix/doc/SuiteSparse/README.md
/usr/lib/R/library/Matrix/doc/index.html
/usr/lib/R/library/Matrix/doc/sparseModels.R
/usr/lib/R/library/Matrix/doc/Design-issues.R
/usr/lib/R/library/Matrix/doc/Comparisons.Rnw
/usr/lib/R/library/Matrix/doc/Introduction.Rnw
/usr/lib/R/library/Matrix/doc/Intro2Matrix.Rnw
/usr/lib/R/library/Matrix/doc/Intro2Matrix.R
/usr/lib/R/library/Matrix/doc/sparseModels.pdf
/usr/lib/R/library/Matrix/doc/Design-issues.pdf
/usr/lib/R/library/Matrix/INDEX
/usr/lib/R/library/Matrix/scripts/SuiteSparse.patch
/usr/lib/R/library/Matrix/scripts/disclaimer.txt
/usr/lib/R/library/Matrix/scripts/rules.sh
/usr/lib/R/library/Matrix/scripts/sources.mk
/usr/lib/R/library/Matrix/scripts/cholmod.h.patch
/usr/lib/R/library/Matrix/scripts/rules.mk
/usr/lib/R/library/Matrix/scripts/ssget.sh
/usr/lib/R/library/Matrix/data/USCounties.R
/usr/lib/R/library/Matrix/data/wrld_1deg.R
/usr/lib/R/library/Matrix/data/datalist
/usr/lib/R/library/Matrix/data/KNex.R
/usr/lib/R/library/Matrix/data/CAex.R
/usr/lib/R/library/Matrix/test-tools-Matrix.R
/usr/lib/R/library/Matrix/LICENCE
/usr/lib/R/library/Matrix/po/en@quot/LC_MESSAGES/R-Matrix.mo
/usr/lib/R/library/Matrix/po/en@quot/LC_MESSAGES/Matrix.mo
/usr/lib/R/library/Matrix/po/lt/LC_MESSAGES/R-Matrix.mo
/usr/lib/R/library/Matrix/po/lt/LC_MESSAGES/Matrix.mo
/usr/lib/R/library/Matrix/po/it/LC_MESSAGES/R-Matrix.mo
/usr/lib/R/library/Matrix/po/it/LC_MESSAGES/Matrix.mo
/usr/lib/R/library/Matrix/po/fr/LC_MESSAGES/R-Matrix.mo
/usr/lib/R/library/Matrix/po/fr/LC_MESSAGES/Matrix.mo
/usr/lib/R/library/Matrix/po/ko/LC_MESSAGES/R-Matrix.mo
/usr/lib/R/library/Matrix/po/ko/LC_MESSAGES/Matrix.mo
/usr/lib/R/library/Matrix/po/de/LC_MESSAGES/R-Matrix.mo
/usr/lib/R/library/Matrix/po/de/LC_MESSAGES/Matrix.mo
/usr/lib/R/library/Matrix/po/pl/LC_MESSAGES/R-Matrix.mo
/usr/lib/R/library/Matrix/po/pl/LC_MESSAGES/Matrix.mo
/usr/lib/R/library/Matrix/html/R.css
/usr/lib/R/library/Matrix/html/00Index.html
/usr/lib/R/library/Matrix/R/Matrix
/usr/lib/R/library/Matrix/R/Matrix.rdb
/usr/lib/R/library/Matrix/R/Matrix.rdx
/usr/lib/R/library/Matrix/DESCRIPTION
/usr/lib/R/library/Matrix/libs/Matrix.so
/usr/lib/R/library/Matrix/help/Matrix.rdb
/usr/lib/R/library/Matrix/help/aliases.rds
/usr/lib/R/library/Matrix/help/Matrix.rdx
/usr/lib/R/library/Matrix/help/macros/local.Rd
/usr/lib/R/library/Matrix/help/AnIndex
/usr/lib/R/library/Matrix/help/paths.rds
/usr/lib/R/library/Matrix/Meta/Rd.rds
/usr/lib/R/library/Matrix/Meta/data.rds
/usr/lib/R/library/Matrix/Meta/links.rds
/usr/lib/R/library/Matrix/Meta/vignette.rds
/usr/lib/R/library/Matrix/Meta/features.rds
/usr/lib/R/library/Matrix/Meta/package.rds
/usr/lib/R/library/Matrix/Meta/hsearch.rds
/usr/lib/R/library/Matrix/Meta/nsInfo.rds
/usr/lib/R/library/Matrix/NAMESPACE
/usr/lib/R/library/Matrix/test-tools.R
/usr/lib/R/library/Matrix/NEWS.Rd
/usr/lib/R/library/Matrix/external/Z_NA_rnk.rds
/usr/lib/R/library/Matrix/external/test3comp.rda
/usr/lib/R/library/Matrix/external/utm300.rua
/usr/lib/R/library/Matrix/external/pores_1.mtx
/usr/lib/R/library/Matrix/external/KNex_slots.rda
/usr/lib/R/library/Matrix/external/jgl009.mtx
/usr/lib/R/library/Matrix/external/lund_a.rsa
/usr/lib/R/library/Matrix/external/symA.rda
/usr/lib/R/library/Matrix/external/wrong.mtx
/usr/lib/R/library/Matrix/external/USCounties_slots.rda
/usr/lib/R/library/Matrix/external/symW.rda
/usr/lib/R/library/Matrix/external/lund_a.mtx
/usr/lib/R/library/Matrix/external/CAex_slots.rda
/usr/lib/R/library/Matrix/external/wrld_1deg_slots.rda
/usr/lib/R/library/Matrix/test-tools-1.R
/usr/lib/R/library/Matrix/include/Matrix/remap.h
/usr/lib/R/library/Matrix/include/Matrix/cholmod-utils.h
/usr/lib/R/library/Matrix/include/Matrix/alloca.h
/usr/lib/R/library/Matrix/include/Matrix/stubs.c
/usr/lib/R/library/Matrix/include/Matrix/Matrix.h
/usr/lib/R/library/Matrix/include/Matrix/version.h
/usr/lib/R/library/Matrix/include/Matrix/cholmod.h
/usr/lib/R/library/Matrix/include/Matrix.h
/usr/lib/R/library/Matrix/include/Matrix_stubs.c
/usr/lib/R/library/Matrix/include/cholmod.h
/usr/lib/R/library/lattice/doc/grid.R
/usr/lib/R/library/lattice/doc/grid.Rnw
/usr/lib/R/library/lattice/doc/grid.pdf
/usr/lib/R/library/lattice/doc/index.html
/usr/lib/R/library/lattice/INDEX
/usr/lib/R/library/lattice/data/Rdata.rdx
/usr/lib/R/library/lattice/data/Rdata.rds
/usr/lib/R/library/lattice/data/Rdata.rdb
/usr/lib/R/library/lattice/NEWS.md
/usr/lib/R/library/lattice/po/en@quot/LC_MESSAGES/R-lattice.mo
/usr/lib/R/library/lattice/po/it/LC_MESSAGES/R-lattice.mo
/usr/lib/R/library/lattice/po/fr/LC_MESSAGES/R-lattice.mo
/usr/lib/R/library/lattice/po/ko/LC_MESSAGES/R-lattice.mo
/usr/lib/R/library/lattice/po/de/LC_MESSAGES/R-lattice.mo
/usr/lib/R/library/lattice/po/pl/LC_MESSAGES/R-lattice.mo
/usr/lib/R/library/lattice/html/R.css
/usr/lib/R/library/lattice/html/00Index.html
/usr/lib/R/library/lattice/R/lattice
/usr/lib/R/library/lattice/R/lattice.rdb
/usr/lib/R/library/lattice/R/lattice.rdx
/usr/lib/R/library/lattice/DESCRIPTION
/usr/lib/R/library/lattice/libs/lattice.so
/usr/lib/R/library/lattice/CITATION
/usr/lib/R/library/lattice/help/lattice.rdb
/usr/lib/R/library/lattice/help/aliases.rds
/usr/lib/R/library/lattice/help/AnIndex
/usr/lib/R/library/lattice/help/figures/logo.svg
/usr/lib/R/library/lattice/help/paths.rds
/usr/lib/R/library/lattice/help/lattice.rdx
/usr/lib/R/library/lattice/Meta/Rd.rds
/usr/lib/R/library/lattice/Meta/data.rds
/usr/lib/R/library/lattice/Meta/links.rds
/usr/lib/R/library/lattice/Meta/vignette.rds
/usr/lib/R/library/lattice/Meta/features.rds
/usr/lib/R/library/lattice/Meta/package.rds
/usr/lib/R/library/lattice/Meta/hsearch.rds
/usr/lib/R/library/lattice/Meta/nsInfo.rds
/usr/lib/R/library/lattice/Meta/demo.rds
/usr/lib/R/library/lattice/NAMESPACE
/usr/lib/R/library/lattice/demo/lattice.R
/usr/lib/R/library/lattice/demo/intervals.R
/usr/lib/R/library/lattice/demo/panel.R
/usr/lib/R/library/lattice/demo/labels.R
/usr/lib/R/library/lattice/README.md
/usr/lib/R/library/KernSmooth/INDEX
/usr/lib/R/library/KernSmooth/po/en@quot/LC_MESSAGES/R-KernSmooth.mo
/usr/lib/R/library/KernSmooth/po/it/LC_MESSAGES/R-KernSmooth.mo
/usr/lib/R/library/KernSmooth/po/fr/LC_MESSAGES/R-KernSmooth.mo
/usr/lib/R/library/KernSmooth/po/ko/LC_MESSAGES/R-KernSmooth.mo
/usr/lib/R/library/KernSmooth/po/de/LC_MESSAGES/R-KernSmooth.mo
/usr/lib/R/library/KernSmooth/po/pl/LC_MESSAGES/R-KernSmooth.mo
/usr/lib/R/library/KernSmooth/html/R.css
/usr/lib/R/library/KernSmooth/html/00Index.html
/usr/lib/R/library/KernSmooth/R/KernSmooth
/usr/lib/R/library/KernSmooth/R/KernSmooth.rdb
/usr/lib/R/library/KernSmooth/R/KernSmooth.rdx
/usr/lib/R/library/KernSmooth/DESCRIPTION
/usr/lib/R/library/KernSmooth/libs/KernSmooth.so
/usr/lib/R/library/KernSmooth/help/aliases.rds
/usr/lib/R/library/KernSmooth/help/KernSmooth.rdb
/usr/lib/R/library/KernSmooth/help/AnIndex
/usr/lib/R/library/KernSmooth/help/KernSmooth.rdx
/usr/lib/R/library/KernSmooth/help/paths.rds
/usr/lib/R/library/KernSmooth/Meta/Rd.rds
/usr/lib/R/library/KernSmooth/Meta/links.rds
/usr/lib/R/library/KernSmooth/Meta/features.rds
/usr/lib/R/library/KernSmooth/Meta/package.rds
/usr/lib/R/library/KernSmooth/Meta/hsearch.rds
/usr/lib/R/library/KernSmooth/Meta/nsInfo.rds
/usr/lib/R/library/KernSmooth/NAMESPACE
/usr/lib/R/library/compiler/INDEX
/usr/lib/R/library/compiler/html/R.css
/usr/lib/R/library/compiler/html/00Index.html
/usr/lib/R/library/compiler/R/compiler
/usr/lib/R/library/compiler/R/compiler.rdb
/usr/lib/R/library/compiler/R/compiler.rdx
/usr/lib/R/library/compiler/DESCRIPTION
/usr/lib/R/library/compiler/help/compiler.rdb
/usr/lib/R/library/compiler/help/aliases.rds
/usr/lib/R/library/compiler/help/compiler.rdx
/usr/lib/R/library/compiler/help/AnIndex
/usr/lib/R/library/compiler/help/paths.rds
/usr/lib/R/library/compiler/Meta/Rd.rds
/usr/lib/R/library/compiler/Meta/links.rds
/usr/lib/R/library/compiler/Meta/features.rds
/usr/lib/R/library/compiler/Meta/package.rds
/usr/lib/R/library/compiler/Meta/hsearch.rds
/usr/lib/R/library/compiler/Meta/nsInfo.rds
/usr/lib/R/library/compiler/NAMESPACE
/usr/lib/R/library/utils/doc/Sweave.pdf
/usr/lib/R/library/utils/INDEX
/usr/lib/R/library/utils/Sweave/example-1.Rnw
/usr/lib/R/library/utils/Sweave/Sweave-test-1.Rnw
/usr/lib/R/library/utils/Sweave/example-2.Rnw
/usr/lib/R/library/utils/Sweave/example-4.Rnw
/usr/lib/R/library/utils/Sweave/example-3.Rnw
/usr/lib/R/library/utils/iconvlist
/usr/lib/R/library/utils/html/R.css
/usr/lib/R/library/utils/html/00Index.html
/usr/lib/R/library/utils/R/utils
/usr/lib/R/library/utils/R/utils.rdb
/usr/lib/R/library/utils/R/utils.rdx
/usr/lib/R/library/utils/R/sysdata.rdb
/usr/lib/R/library/utils/R/sysdata.rdx
/usr/lib/R/library/utils/DESCRIPTION
/usr/lib/R/library/utils/libs/utils.so
/usr/lib/R/library/utils/help/aliases.rds
/usr/lib/R/library/utils/help/utils.rdb
/usr/lib/R/library/utils/help/utils.rdx
/usr/lib/R/library/utils/help/AnIndex
/usr/lib/R/library/utils/help/paths.rds
/usr/lib/R/library/utils/Meta/Rd.rds
/usr/lib/R/library/utils/Meta/links.rds
/usr/lib/R/library/utils/Meta/features.rds
/usr/lib/R/library/utils/Meta/package.rds
/usr/lib/R/library/utils/Meta/hsearch.rds
/usr/lib/R/library/utils/Meta/nsInfo.rds
/usr/lib/R/library/utils/NAMESPACE
/usr/lib/R/library/utils/misc/exDIF.csv
/usr/lib/R/library/utils/misc/exDIF.dif
/usr/lib/R/library/tools/INDEX
/usr/lib/R/library/tools/html/R.css
/usr/lib/R/library/tools/html/00Index.html
/usr/lib/R/library/tools/R/tools
/usr/lib/R/library/tools/R/tools.rdx
/usr/lib/R/library/tools/R/sysdata.rdb
/usr/lib/R/library/tools/R/sysdata.rdx
/usr/lib/R/library/tools/R/tools.rdb
/usr/lib/R/library/tools/DESCRIPTION
/usr/lib/R/library/tools/libs/tools.so
/usr/lib/R/library/tools/help/aliases.rds
/usr/lib/R/library/tools/help/tools.rdx
/usr/lib/R/library/tools/help/AnIndex
/usr/lib/R/library/tools/help/paths.rds
/usr/lib/R/library/tools/help/tools.rdb
/usr/lib/R/library/tools/Meta/Rd.rds
/usr/lib/R/library/tools/Meta/links.rds
/usr/lib/R/library/tools/Meta/features.rds
/usr/lib/R/library/tools/Meta/package.rds
/usr/lib/R/library/tools/Meta/hsearch.rds
/usr/lib/R/library/tools/Meta/nsInfo.rds
/usr/lib/R/library/tools/NAMESPACE
/usr/lib/R/library/tools/misc/top.txt
/usr/lib/R/library/tools/misc/wre.txt
/usr/lib/R/library/foreign/INDEX
/usr/lib/R/library/foreign/po/en@quot/LC_MESSAGES/R-foreign.mo
/usr/lib/R/library/foreign/po/en@quot/LC_MESSAGES/foreign.mo
/usr/lib/R/library/foreign/po/it/LC_MESSAGES/R-foreign.mo
/usr/lib/R/library/foreign/po/it/LC_MESSAGES/foreign.mo
/usr/lib/R/library/foreign/po/fr/LC_MESSAGES/R-foreign.mo
/usr/lib/R/library/foreign/po/fr/LC_MESSAGES/foreign.mo
/usr/lib/R/library/foreign/po/de/LC_MESSAGES/R-foreign.mo
/usr/lib/R/library/foreign/po/de/LC_MESSAGES/foreign.mo
/usr/lib/R/library/foreign/po/pl/LC_MESSAGES/R-foreign.mo
/usr/lib/R/library/foreign/po/pl/LC_MESSAGES/foreign.mo
/usr/lib/R/library/foreign/html/R.css
/usr/lib/R/library/foreign/html/00Index.html
/usr/lib/R/library/foreign/R/foreign
/usr/lib/R/library/foreign/R/foreign.rdb
/usr/lib/R/library/foreign/R/foreign.rdx
/usr/lib/R/library/foreign/DESCRIPTION
/usr/lib/R/library/foreign/libs/foreign.so
/usr/lib/R/library/foreign/help/foreign.rdb
/usr/lib/R/library/foreign/help/aliases.rds
/usr/lib/R/library/foreign/help/AnIndex
/usr/lib/R/library/foreign/help/paths.rds
/usr/lib/R/library/foreign/help/foreign.rdx
/usr/lib/R/library/foreign/Meta/Rd.rds
/usr/lib/R/library/foreign/Meta/links.rds
/usr/lib/R/library/foreign/Meta/features.rds
/usr/lib/R/library/foreign/Meta/package.rds
/usr/lib/R/library/foreign/Meta/hsearch.rds
/usr/lib/R/library/foreign/Meta/nsInfo.rds
/usr/lib/R/library/foreign/NAMESPACE
/usr/lib/R/library/foreign/COPYRIGHTS
/usr/lib/R/library/foreign/files/testdata.sav
/usr/lib/R/library/foreign/files/Iris.syd
/usr/lib/R/library/foreign/files/HillRace.SYD
/usr/lib/R/library/foreign/files/electric.sav
/usr/lib/R/library/foreign/files/sids.dbf
/usr/lib/R/library/parallel/doc/parallel.pdf
/usr/lib/R/library/parallel/INDEX
/usr/lib/R/library/parallel/html/R.css
/usr/lib/R/library/parallel/html/00Index.html
/usr/lib/R/library/parallel/R/parallel.rdb
/usr/lib/R/library/parallel/R/parallel.rdx
/usr/lib/R/library/parallel/R/parallel
/usr/lib/R/library/parallel/DESCRIPTION
/usr/lib/R/library/parallel/libs/parallel.so
/usr/lib/R/library/parallel/help/parallel.rdb
/usr/lib/R/library/parallel/help/parallel.rdx
/usr/lib/R/library/parallel/help/aliases.rds
/usr/lib/R/library/parallel/help/AnIndex
/usr/lib/R/library/parallel/help/paths.rds
/usr/lib/R/library/parallel/Meta/Rd.rds
/usr/lib/R/library/parallel/Meta/links.rds
/usr/lib/R/library/parallel/Meta/features.rds
/usr/lib/R/library/parallel/Meta/package.rds
/usr/lib/R/library/parallel/Meta/hsearch.rds
/usr/lib/R/library/parallel/Meta/nsInfo.rds
/usr/lib/R/library/parallel/NAMESPACE
/usr/lib/R/library/grDevices/INDEX
/usr/lib/R/library/grDevices/icc/srgb.flate
/usr/lib/R/library/grDevices/icc/srgb
/usr/lib/R/library/grDevices/html/R.css
/usr/lib/R/library/grDevices/html/00Index.html
/usr/lib/R/library/grDevices/R/grDevices
/usr/lib/R/library/grDevices/R/grDevices.rdx
/usr/lib/R/library/grDevices/R/grDevices.rdb
/usr/lib/R/library/grDevices/DESCRIPTION
/usr/lib/R/library/grDevices/libs/grDevices.so
/usr/lib/R/library/grDevices/libs/cairo.so
/usr/lib/R/library/grDevices/help/aliases.rds
/usr/lib/R/library/grDevices/help/grDevices.rdx
/usr/lib/R/library/grDevices/help/grDevices.rdb
/usr/lib/R/library/grDevices/help/AnIndex
/usr/lib/R/library/grDevices/help/paths.rds
/usr/lib/R/library/grDevices/fonts/Roboto/LICENSE.txt
/usr/lib/R/library/grDevices/fonts/Roboto/Roboto-Medium.ttf
/usr/lib/R/library/grDevices/fonts/Montserrat/static/Montserrat-Medium.ttf
/usr/lib/R/library/grDevices/fonts/Montserrat/static/Montserrat-BoldItalic.ttf
/usr/lib/R/library/grDevices/afm/Times-Italic.afm.gz
/usr/lib/R/library/grDevices/afm/n019004l.afm.gz
/usr/lib/R/library/grDevices/afm/bkli____.afm.gz
/usr/lib/R/library/grDevices/afm/c059013l.afm.gz
/usr/lib/R/library/grDevices/afm/cmti10.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusSans-Bold.afm.gz
/usr/lib/R/library/grDevices/afm/ncr_____.afm.gz
/usr/lib/R/library/grDevices/afm/Times-BoldItalic.afm.gz
/usr/lib/R/library/grDevices/afm/ArialMT-BoldItalic.afm.gz
/usr/lib/R/library/grDevices/afm/ncbi____.afm.gz
/usr/lib/R/library/grDevices/afm/b018012l.afm.gz
/usr/lib/R/library/grDevices/afm/MustRead.html
/usr/lib/R/library/grDevices/afm/a010033l.afm.gz
/usr/lib/R/library/grDevices/afm/hvnb____.afm.gz
/usr/lib/R/library/grDevices/afm/c059033l.afm.gz
/usr/lib/R/library/grDevices/afm/n019003l.afm.gz
/usr/lib/R/library/grDevices/afm/ncb_____.afm.gz
/usr/lib/R/library/grDevices/afm/CM_boldx_italic_10.afm.gz
/usr/lib/R/library/grDevices/afm/pobi____.afm.gz
/usr/lib/R/library/grDevices/afm/hvo_____.afm.gz
/usr/lib/R/library/grDevices/afm/b018032l.afm.gz
/usr/lib/R/library/grDevices/afm/Times-Bold.afm.gz
/usr/lib/R/library/grDevices/afm/Helvetica-Bold.afm.gz
/usr/lib/R/library/grDevices/afm/n019044l.afm.gz
/usr/lib/R/library/grDevices/afm/hvn_____.afm.gz
/usr/lib/R/library/grDevices/afm/ArialMT-Bold.afm.gz
/usr/lib/R/library/grDevices/afm/tir_____.afm.gz
/usr/lib/R/library/grDevices/afm/bkd_____.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusMonoPS-Italic.afm.gz
/usr/lib/R/library/grDevices/afm/cmbxti10.afm.gz
/usr/lib/R/library/grDevices/afm/agd_____.afm.gz
/usr/lib/R/library/grDevices/afm/ZapfDingbats.afm.gz
/usr/lib/R/library/grDevices/afm/n022003l.afm.gz
/usr/lib/R/library/grDevices/afm/Courier-BoldOblique.afm.gz
/usr/lib/R/library/grDevices/afm/por_____.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusSans-Italic.afm.gz
/usr/lib/R/library/grDevices/afm/README
/usr/lib/R/library/grDevices/afm/com_____.afm.gz
/usr/lib/R/library/grDevices/afm/bkdi____.afm.gz
/usr/lib/R/library/grDevices/afm/a010035l.afm.gz
/usr/lib/R/library/grDevices/afm/n021023l.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusMonoPS-Bold.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusSans-BoldItalic.afm.gz
/usr/lib/R/library/grDevices/afm/c059036l.afm.gz
/usr/lib/R/library/grDevices/afm/n022023l.afm.gz
/usr/lib/R/library/grDevices/afm/Courier-Bold.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusMonoPS-Regular.afm.gz
/usr/lib/R/library/grDevices/afm/tibi____.afm.gz
/usr/lib/R/library/grDevices/afm/poi_____.afm.gz
/usr/lib/R/library/grDevices/afm/hvnbo___.afm.gz
/usr/lib/R/library/grDevices/afm/Helvetica-Oblique.afm.gz
/usr/lib/R/library/grDevices/afm/hvbo____.afm.gz
/usr/lib/R/library/grDevices/afm/hv______.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusRoman-Regular.afm.gz
/usr/lib/R/library/grDevices/afm/a010013l.afm.gz
/usr/lib/R/library/grDevices/afm/agwo____.afm.gz
/usr/lib/R/library/grDevices/afm/CM_symbol_10.afm.gz
/usr/lib/R/library/grDevices/afm/n019043l.afm.gz
/usr/lib/R/library/grDevices/afm/n019024l.afm.gz
/usr/lib/R/library/grDevices/afm/n019064l.afm.gz
/usr/lib/R/library/grDevices/afm/ArialMT-Italic.afm.gz
/usr/lib/R/library/grDevices/afm/n019023l.afm.gz
/usr/lib/R/library/grDevices/afm/n022004l.afm.gz
/usr/lib/R/library/grDevices/afm/coo_____.afm.gz
/usr/lib/R/library/grDevices/afm/StandardSymbolsPS.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusMonoPS-BoldItalic.afm.gz
/usr/lib/R/library/grDevices/afm/Helvetica.afm.gz
/usr/lib/R/library/grDevices/afm/Times-Roman.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusRoman-BoldItalic.afm.gz
/usr/lib/R/library/grDevices/afm/tii_____.afm.gz
/usr/lib/R/library/grDevices/afm/p052003l.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusSans-Oblique.afm.gz
/usr/lib/R/library/grDevices/afm/cobo____.afm.gz
/usr/lib/R/library/grDevices/afm/LICENSE.LPPL
/usr/lib/R/library/grDevices/afm/hvb_____.afm.gz
/usr/lib/R/library/grDevices/afm/CM_regular_10.afm.gz
/usr/lib/R/library/grDevices/afm/a010015l.afm.gz
/usr/lib/R/library/grDevices/afm/s050000l.afm.gz
/usr/lib/R/library/grDevices/afm/sy______.afm.gz
/usr/lib/R/library/grDevices/afm/n019063l.afm.gz
/usr/lib/R/library/grDevices/afm/Helvetica-BoldOblique.afm.gz
/usr/lib/R/library/grDevices/afm/p052024l.afm.gz
/usr/lib/R/library/grDevices/afm/bkl_____.afm.gz
/usr/lib/R/library/grDevices/afm/CM_italic_10.afm.gz
/usr/lib/R/library/grDevices/afm/n021004l.afm.gz
/usr/lib/R/library/grDevices/afm/tib_____.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusSans-BoldOblique.afm.gz
/usr/lib/R/library/grDevices/afm/Courier-Oblique.afm.gz
/usr/lib/R/library/grDevices/afm/nci_____.afm.gz
/usr/lib/R/library/grDevices/afm/hvno____.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusRoman-Italic.afm.gz
/usr/lib/R/library/grDevices/afm/n021003l.afm.gz
/usr/lib/R/library/grDevices/afm/n021024l.afm.gz
/usr/lib/R/library/grDevices/afm/p052004l.afm.gz
/usr/lib/R/library/grDevices/afm/ArialMT.afm.gz
/usr/lib/R/library/grDevices/afm/agw_____.afm.gz
/usr/lib/R/library/grDevices/afm/pob_____.afm.gz
/usr/lib/R/library/grDevices/afm/p052023l.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusSans-Regular.afm.gz
/usr/lib/R/library/grDevices/afm/NimbusRoman-Bold.afm.gz
/usr/lib/R/library/grDevices/afm/Symbol.afm.gz
/usr/lib/R/library/grDevices/afm/cob_____.afm.gz
/usr/lib/R/library/grDevices/afm/n022024l.afm.gz
/usr/lib/R/library/grDevices/afm/b018035l.afm.gz
/usr/lib/R/library/grDevices/afm/b018015l.afm.gz
/usr/lib/R/library/grDevices/afm/CM_boldx_10.afm.gz
/usr/lib/R/library/grDevices/afm/Courier.afm.gz
/usr/lib/R/library/grDevices/afm/agdo____.afm.gz
/usr/lib/R/library/grDevices/afm/c059016l.afm.gz
/usr/lib/R/library/grDevices/Meta/Rd.rds
/usr/lib/R/library/grDevices/Meta/links.rds
/usr/lib/R/library/grDevices/Meta/features.rds
/usr/lib/R/library/grDevices/Meta/package.rds
/usr/lib/R/library/grDevices/Meta/hsearch.rds
/usr/lib/R/library/grDevices/Meta/nsInfo.rds
/usr/lib/R/library/grDevices/Meta/demo.rds
/usr/lib/R/library/grDevices/NAMESPACE
/usr/lib/R/library/grDevices/demo/hclColors.R
/usr/lib/R/library/grDevices/demo/colors.R
/usr/lib/R/library/grDevices/enc/CP1253.enc
/usr/lib/R/library/grDevices/enc/ISOLatin2.enc
/usr/lib/R/library/grDevices/enc/AdobeStd.enc
/usr/lib/R/library/grDevices/enc/CP1257.enc
/usr/lib/R/library/grDevices/enc/Greek.enc
/usr/lib/R/library/grDevices/enc/CP1251.enc
/usr/lib/R/library/grDevices/enc/ISOLatin1.enc
/usr/lib/R/library/grDevices/enc/AdobeSym.enc
/usr/lib/R/library/grDevices/enc/Cyrillic.enc
/usr/lib/R/library/grDevices/enc/PDFDoc.enc
/usr/lib/R/library/grDevices/enc/KOI8-R.enc
/usr/lib/R/library/grDevices/enc/TeXtext.enc
/usr/lib/R/library/grDevices/enc/CP1250.enc
/usr/lib/R/library/grDevices/enc/KOI8-U.enc
/usr/lib/R/library/grDevices/enc/WinAnsi.enc
/usr/lib/R/library/grDevices/enc/ISOLatin7.enc
/usr/lib/R/library/grDevices/enc/ISOLatin9.enc
/usr/lib/R/library/boot/INDEX
/usr/lib/R/library/boot/data/Rdata.rdx
/usr/lib/R/library/boot/data/Rdata.rds
/usr/lib/R/library/boot/data/Rdata.rdb
/usr/lib/R/library/boot/po/en@quot/LC_MESSAGES/R-boot.mo
/usr/lib/R/library/boot/po/it/LC_MESSAGES/R-boot.mo
/usr/lib/R/library/boot/po/fr/LC_MESSAGES/R-boot.mo
/usr/lib/R/library/boot/po/ko/LC_MESSAGES/R-boot.mo
/usr/lib/R/library/boot/po/de/LC_MESSAGES/R-boot.mo
/usr/lib/R/library/boot/po/ru/LC_MESSAGES/R-boot.mo
/usr/lib/R/library/boot/po/pl/LC_MESSAGES/R-boot.mo
/usr/lib/R/library/boot/html/R.css
/usr/lib/R/library/boot/html/00Index.html
/usr/lib/R/library/boot/R/boot
/usr/lib/R/library/boot/R/boot.rdb
/usr/lib/R/library/boot/R/boot.rdx
/usr/lib/R/library/boot/DESCRIPTION
/usr/lib/R/library/boot/CITATION
/usr/lib/R/library/boot/help/aliases.rds
/usr/lib/R/library/boot/help/boot.rdb
/usr/lib/R/library/boot/help/boot.rdx
/usr/lib/R/library/boot/help/AnIndex
/usr/lib/R/library/boot/help/paths.rds
/usr/lib/R/library/boot/Meta/Rd.rds
/usr/lib/R/library/boot/Meta/data.rds
/usr/lib/R/library/boot/Meta/links.rds
/usr/lib/R/library/boot/Meta/features.rds
/usr/lib/R/library/boot/Meta/package.rds
/usr/lib/R/library/boot/Meta/hsearch.rds
/usr/lib/R/library/boot/Meta/nsInfo.rds
/usr/lib/R/library/boot/NAMESPACE
/usr/lib/R/library/boot/bd.q
/usr/lib/R/library/spatial/INDEX
/usr/lib/R/library/spatial/PP.files
/usr/lib/R/library/spatial/po/en@quot/LC_MESSAGES/R-spatial.mo
/usr/lib/R/library/spatial/po/it/LC_MESSAGES/R-spatial.mo
/usr/lib/R/library/spatial/po/fr/LC_MESSAGES/R-spatial.mo
/usr/lib/R/library/spatial/po/ko/LC_MESSAGES/R-spatial.mo
/usr/lib/R/library/spatial/po/de/LC_MESSAGES/R-spatial.mo
/usr/lib/R/library/spatial/po/pl/LC_MESSAGES/R-spatial.mo
/usr/lib/R/library/spatial/html/R.css
/usr/lib/R/library/spatial/html/00Index.html
/usr/lib/R/library/spatial/R/spatial
/usr/lib/R/library/spatial/R/spatial.rdb
/usr/lib/R/library/spatial/R/spatial.rdx
/usr/lib/R/library/spatial/DESCRIPTION
/usr/lib/R/library/spatial/libs/spatial.so
/usr/lib/R/library/spatial/ppdata/pairfn.dat
/usr/lib/R/library/spatial/ppdata/fig3a.dat
/usr/lib/R/library/spatial/ppdata/cells.dat
/usr/lib/R/library/spatial/ppdata/nztrees.dat
/usr/lib/R/library/spatial/ppdata/agter.dat
/usr/lib/R/library/spatial/ppdata/pines.dat
/usr/lib/R/library/spatial/ppdata/stowns1.dat
/usr/lib/R/library/spatial/ppdata/eagles.dat
/usr/lib/R/library/spatial/ppdata/tokyo.dat
/usr/lib/R/library/spatial/ppdata/drumlin.dat
/usr/lib/R/library/spatial/ppdata/fig2a.dat
/usr/lib/R/library/spatial/ppdata/schools.dat
/usr/lib/R/library/spatial/ppdata/fig3c.dat
/usr/lib/R/library/spatial/ppdata/pereg.dat
/usr/lib/R/library/spatial/ppdata/caveolae.dat
/usr/lib/R/library/spatial/ppdata/redwood.dat
/usr/lib/R/library/spatial/ppdata/fig1b.dat
/usr/lib/R/library/spatial/ppdata/grocery.dat
/usr/lib/R/library/spatial/ppdata/towns.dat
/usr/lib/R/library/spatial/ppdata/fig2b.dat
/usr/lib/R/library/spatial/ppdata/fig1c.dat
/usr/lib/R/library/spatial/ppdata/hccells.dat
/usr/lib/R/library/spatial/ppdata/fig3b.dat
/usr/lib/R/library/spatial/ppdata/davis.dat
/usr/lib/R/library/spatial/CITATION
/usr/lib/R/library/spatial/help/aliases.rds
/usr/lib/R/library/spatial/help/spatial.rdb
/usr/lib/R/library/spatial/help/spatial.rdx
/usr/lib/R/library/spatial/help/AnIndex
/usr/lib/R/library/spatial/help/paths.rds
/usr/lib/R/library/spatial/NEWS
/usr/lib/R/library/spatial/Meta/Rd.rds
/usr/lib/R/library/spatial/Meta/links.rds
/usr/lib/R/library/spatial/Meta/features.rds
/usr/lib/R/library/spatial/Meta/package.rds
/usr/lib/R/library/spatial/Meta/hsearch.rds
/usr/lib/R/library/spatial/Meta/nsInfo.rds
/usr/lib/R/library/spatial/NAMESPACE
/usr/lib/R/library/rpart/doc/usercode.Rnw
/usr/lib/R/library/rpart/doc/longintro.Rnw
/usr/lib/R/library/rpart/doc/usercode.pdf
/usr/lib/R/library/rpart/doc/longintro.R
/usr/lib/R/library/rpart/doc/longintro.pdf
/usr/lib/R/library/rpart/doc/index.html
/usr/lib/R/library/rpart/doc/usercode.R
/usr/lib/R/library/rpart/INDEX
/usr/lib/R/library/rpart/data/Rdata.rdx
/usr/lib/R/library/rpart/data/Rdata.rds
/usr/lib/R/library/rpart/data/Rdata.rdb
/usr/lib/R/library/rpart/po/en@quot/LC_MESSAGES/R-rpart.mo
/usr/lib/R/library/rpart/po/en@quot/LC_MESSAGES/rpart.mo
/usr/lib/R/library/rpart/po/fr/LC_MESSAGES/R-rpart.mo
/usr/lib/R/library/rpart/po/fr/LC_MESSAGES/rpart.mo
/usr/lib/R/library/rpart/po/ko/LC_MESSAGES/R-rpart.mo
/usr/lib/R/library/rpart/po/ko/LC_MESSAGES/rpart.mo
/usr/lib/R/library/rpart/po/de/LC_MESSAGES/R-rpart.mo
/usr/lib/R/library/rpart/po/de/LC_MESSAGES/rpart.mo
/usr/lib/R/library/rpart/po/ru/LC_MESSAGES/R-rpart.mo
/usr/lib/R/library/rpart/po/ru/LC_MESSAGES/rpart.mo
/usr/lib/R/library/rpart/po/pl/LC_MESSAGES/R-rpart.mo
/usr/lib/R/library/rpart/po/pl/LC_MESSAGES/rpart.mo
/usr/lib/R/library/rpart/html/R.css
/usr/lib/R/library/rpart/html/00Index.html
/usr/lib/R/library/rpart/R/rpart.rdx
/usr/lib/R/library/rpart/R/rpart
/usr/lib/R/library/rpart/R/rpart.rdb
/usr/lib/R/library/rpart/DESCRIPTION
/usr/lib/R/library/rpart/libs/rpart.so
/usr/lib/R/library/rpart/help/rpart.rdx
/usr/lib/R/library/rpart/help/aliases.rds
/usr/lib/R/library/rpart/help/AnIndex
/usr/lib/R/library/rpart/help/figures/rpart.png
/usr/lib/R/library/rpart/help/paths.rds
/usr/lib/R/library/rpart/help/rpart.rdb
/usr/lib/R/library/rpart/Meta/Rd.rds
/usr/lib/R/library/rpart/Meta/data.rds
/usr/lib/R/library/rpart/Meta/links.rds
/usr/lib/R/library/rpart/Meta/vignette.rds
/usr/lib/R/library/rpart/Meta/features.rds
/usr/lib/R/library/rpart/Meta/package.rds
/usr/lib/R/library/rpart/Meta/hsearch.rds
/usr/lib/R/library/rpart/Meta/nsInfo.rds
/usr/lib/R/library/rpart/NAMESPACE
/usr/lib/R/library/rpart/NEWS.Rd
/usr/lib/R/library/rpart/README.md
/usr/lib/R/library/nlme/INDEX
/usr/lib/R/library/nlme/scripts/ch08.R
/usr/lib/R/library/nlme/scripts/ch03.R
/usr/lib/R/library/nlme/scripts/ch01.R
/usr/lib/R/library/nlme/scripts/runme.R
/usr/lib/R/library/nlme/scripts/sims.rda
/usr/lib/R/library/nlme/scripts/ch02.R
/usr/lib/R/library/nlme/scripts/ch06.R
/usr/lib/R/library/nlme/scripts/ch04.R
/usr/lib/R/library/nlme/scripts/ch05.R
/usr/lib/R/library/nlme/data/Rdata.rdx
/usr/lib/R/library/nlme/data/Rdata.rds
/usr/lib/R/library/nlme/data/Rdata.rdb
/usr/lib/R/library/nlme/po/en@quot/LC_MESSAGES/nlme.mo
/usr/lib/R/library/nlme/po/en@quot/LC_MESSAGES/R-nlme.mo
/usr/lib/R/library/nlme/po/fr/LC_MESSAGES/nlme.mo
/usr/lib/R/library/nlme/po/fr/LC_MESSAGES/R-nlme.mo
/usr/lib/R/library/nlme/po/ko/LC_MESSAGES/nlme.mo
/usr/lib/R/library/nlme/po/ko/LC_MESSAGES/R-nlme.mo
/usr/lib/R/library/nlme/po/de/LC_MESSAGES/nlme.mo
/usr/lib/R/library/nlme/po/de/LC_MESSAGES/R-nlme.mo
/usr/lib/R/library/nlme/po/pl/LC_MESSAGES/nlme.mo
/usr/lib/R/library/nlme/po/pl/LC_MESSAGES/R-nlme.mo
/usr/lib/R/library/nlme/html/R.css
/usr/lib/R/library/nlme/html/00Index.html
/usr/lib/R/library/nlme/R/nlme.rdx
/usr/lib/R/library/nlme/R/nlme.rdb
/usr/lib/R/library/nlme/R/nlme
/usr/lib/R/library/nlme/DESCRIPTION
/usr/lib/R/library/nlme/libs/nlme.so
/usr/lib/R/library/nlme/mlbook/README
/usr/lib/R/library/nlme/mlbook/ch04.R
/usr/lib/R/library/nlme/mlbook/ch05.R
/usr/lib/R/library/nlme/CITATION
/usr/lib/R/library/nlme/help/nlme.rdx
/usr/lib/R/library/nlme/help/nlme.rdb
/usr/lib/R/library/nlme/help/aliases.rds
/usr/lib/R/library/nlme/help/AnIndex
/usr/lib/R/library/nlme/help/paths.rds
/usr/lib/R/library/nlme/Meta/Rd.rds
/usr/lib/R/library/nlme/Meta/data.rds
/usr/lib/R/library/nlme/Meta/links.rds
/usr/lib/R/library/nlme/Meta/features.rds
/usr/lib/R/library/nlme/Meta/package.rds
/usr/lib/R/library/nlme/Meta/hsearch.rds
/usr/lib/R/library/nlme/Meta/nsInfo.rds
/usr/lib/R/library/nlme/NAMESPACE
/usr/lib/R/library/class/INDEX
/usr/lib/R/library/class/po/en@quot/LC_MESSAGES/R-class.mo
/usr/lib/R/library/class/po/it/LC_MESSAGES/R-class.mo
/usr/lib/R/library/class/po/fr/LC_MESSAGES/R-class.mo
/usr/lib/R/library/class/po/ko/LC_MESSAGES/R-class.mo
/usr/lib/R/library/class/po/de/LC_MESSAGES/R-class.mo
/usr/lib/R/library/class/po/pl/LC_MESSAGES/R-class.mo
/usr/lib/R/library/class/html/R.css
/usr/lib/R/library/class/html/00Index.html
/usr/lib/R/library/class/R/class.rdb
/usr/lib/R/library/class/R/class
/usr/lib/R/library/class/R/class.rdx
/usr/lib/R/library/class/DESCRIPTION
/usr/lib/R/library/class/libs/class.so
/usr/lib/R/library/class/CITATION
/usr/lib/R/library/class/help/aliases.rds
/usr/lib/R/library/class/help/class.rdb
/usr/lib/R/library/class/help/AnIndex
/usr/lib/R/library/class/help/class.rdx
/usr/lib/R/library/class/help/paths.rds
/usr/lib/R/library/class/NEWS
/usr/lib/R/library/class/Meta/Rd.rds
/usr/lib/R/library/class/Meta/links.rds
/usr/lib/R/library/class/Meta/features.rds
/usr/lib/R/library/class/Meta/package.rds
/usr/lib/R/library/class/Meta/hsearch.rds
/usr/lib/R/library/class/Meta/nsInfo.rds
/usr/lib/R/library/class/NAMESPACE
/usr/lib/R/library/nnet/INDEX
/usr/lib/R/library/nnet/po/en@quot/LC_MESSAGES/R-nnet.mo
/usr/lib/R/library/nnet/po/it/LC_MESSAGES/R-nnet.mo
/usr/lib/R/library/nnet/po/fr/LC_MESSAGES/R-nnet.mo
/usr/lib/R/library/nnet/po/ko/LC_MESSAGES/R-nnet.mo
/usr/lib/R/library/nnet/po/de/LC_MESSAGES/R-nnet.mo
/usr/lib/R/library/nnet/po/pl/LC_MESSAGES/R-nnet.mo
/usr/lib/R/library/nnet/html/R.css
/usr/lib/R/library/nnet/html/00Index.html
/usr/lib/R/library/nnet/R/nnet.rdb
/usr/lib/R/library/nnet/R/nnet
/usr/lib/R/library/nnet/R/nnet.rdx
/usr/lib/R/library/nnet/DESCRIPTION
/usr/lib/R/library/nnet/libs/nnet.so
/usr/lib/R/library/nnet/CITATION
/usr/lib/R/library/nnet/help/nnet.rdb
/usr/lib/R/library/nnet/help/aliases.rds
/usr/lib/R/library/nnet/help/AnIndex
/usr/lib/R/library/nnet/help/nnet.rdx
/usr/lib/R/library/nnet/help/paths.rds
/usr/lib/R/library/nnet/NEWS
/usr/lib/R/library/nnet/Meta/Rd.rds
/usr/lib/R/library/nnet/Meta/links.rds
/usr/lib/R/library/nnet/Meta/features.rds
/usr/lib/R/library/nnet/Meta/package.rds
/usr/lib/R/library/nnet/Meta/hsearch.rds
/usr/lib/R/library/nnet/Meta/nsInfo.rds
/usr/lib/R/library/nnet/NAMESPACE
/usr/lib/R/library/stats4/INDEX
/usr/lib/R/library/stats4/html/R.css
/usr/lib/R/library/stats4/html/00Index.html
/usr/lib/R/library/stats4/R/stats4.rdx
/usr/lib/R/library/stats4/R/stats4
/usr/lib/R/library/stats4/R/stats4.rdb
/usr/lib/R/library/stats4/DESCRIPTION
/usr/lib/R/library/stats4/help/stats4.rdx
/usr/lib/R/library/stats4/help/aliases.rds
/usr/lib/R/library/stats4/help/stats4.rdb
/usr/lib/R/library/stats4/help/AnIndex
/usr/lib/R/library/stats4/help/paths.rds
/usr/lib/R/library/stats4/Meta/Rd.rds
/usr/lib/R/library/stats4/Meta/links.rds
/usr/lib/R/library/stats4/Meta/features.rds
/usr/lib/R/library/stats4/Meta/package.rds
/usr/lib/R/library/stats4/Meta/hsearch.rds
/usr/lib/R/library/stats4/Meta/nsInfo.rds
/usr/lib/R/library/stats4/NAMESPACE
/usr/lib/R/library/codetools/INDEX
/usr/lib/R/library/codetools/html/R.css
/usr/lib/R/library/codetools/html/00Index.html
/usr/lib/R/library/codetools/R/codetools.rdb
/usr/lib/R/library/codetools/R/codetools
/usr/lib/R/library/codetools/R/codetools.rdx
/usr/lib/R/library/codetools/DESCRIPTION
/usr/lib/R/library/codetools/help/codetools.rdb
/usr/lib/R/library/codetools/help/aliases.rds
/usr/lib/R/library/codetools/help/AnIndex
/usr/lib/R/library/codetools/help/codetools.rdx
/usr/lib/R/library/codetools/help/paths.rds
/usr/lib/R/library/codetools/Meta/Rd.rds
/usr/lib/R/library/codetools/Meta/links.rds
/usr/lib/R/library/codetools/Meta/features.rds
/usr/lib/R/library/codetools/Meta/package.rds
/usr/lib/R/library/codetools/Meta/hsearch.rds
/usr/lib/R/library/codetools/Meta/nsInfo.rds
/usr/lib/R/library/codetools/NAMESPACE
/usr/lib/R/library/grid/doc/frame.pdf
/usr/lib/R/library/grid/doc/changes.txt
/usr/lib/R/library/grid/doc/locndimn.pdf
/usr/lib/R/library/grid/doc/rotated.pdf
/usr/lib/R/library/grid/doc/saveload.pdf
/usr/lib/R/library/grid/doc/viewports.pdf
/usr/lib/R/library/grid/doc/interactive.pdf
/usr/lib/R/library/grid/doc/DivByZero.txt
/usr/lib/R/library/grid/doc/moveline.pdf
/usr/lib/R/library/grid/doc/plotexample.pdf
/usr/lib/R/library/grid/doc/grobs.pdf
/usr/lib/R/library/grid/doc/grid.pdf
/usr/lib/R/library/grid/doc/displaylist.pdf
/usr/lib/R/library/grid/doc/sharing.pdf
/usr/lib/R/library/grid/doc/nonfinite.pdf
/usr/lib/R/library/grid/INDEX
/usr/lib/R/library/grid/html/R.css
/usr/lib/R/library/grid/html/00Index.html
/usr/lib/R/library/grid/R/grid.rdx
/usr/lib/R/library/grid/R/grid
/usr/lib/R/library/grid/R/grid.rdb
/usr/lib/R/library/grid/DESCRIPTION
/usr/lib/R/library/grid/libs/grid.so
/usr/lib/R/library/grid/help/aliases.rds
/usr/lib/R/library/grid/help/grid.rdx
/usr/lib/R/library/grid/help/grid.rdb
/usr/lib/R/library/grid/help/AnIndex
/usr/lib/R/library/grid/help/paths.rds
/usr/lib/R/library/grid/Meta/Rd.rds
/usr/lib/R/library/grid/Meta/links.rds
/usr/lib/R/library/grid/Meta/features.rds
/usr/lib/R/library/grid/Meta/package.rds
/usr/lib/R/library/grid/Meta/hsearch.rds
/usr/lib/R/library/grid/Meta/nsInfo.rds
/usr/lib/R/library/grid/NAMESPACE
/usr/lib/R/library/base/INDEX
/usr/lib/R/library/base/html/R.css
/usr/lib/R/library/base/html/00Index.html
/usr/lib/R/library/base/R/Rprofile
/usr/lib/R/library/base/R/base.rdb
/usr/lib/R/library/base/R/base
/usr/lib/R/library/base/R/base.rdx
/usr/lib/R/library/base/DESCRIPTION
/usr/lib/R/library/base/CITATION
/usr/lib/R/library/base/help/aliases.rds
/usr/lib/R/library/base/help/base.rdb
/usr/lib/R/library/base/help/AnIndex
/usr/lib/R/library/base/help/base.rdx
/usr/lib/R/library/base/help/paths.rds
/usr/lib/R/library/base/Meta/Rd.rds
/usr/lib/R/library/base/Meta/links.rds
/usr/lib/R/library/base/Meta/features.rds
/usr/lib/R/library/base/Meta/package.rds
/usr/lib/R/library/base/Meta/hsearch.rds
/usr/lib/R/library/base/Meta/demo.rds
/usr/lib/R/library/base/demo/scoping.R
/usr/lib/R/library/base/demo/recursion.R
/usr/lib/R/library/base/demo/is.things.R
/usr/lib/R/library/base/demo/error.catching.R
/usr/lib/R/library/MASS/INDEX
/usr/lib/R/library/MASS/scripts/ch08.R
/usr/lib/R/library/MASS/scripts/ch03.R
/usr/lib/R/library/MASS/scripts/ch01.R
/usr/lib/R/library/MASS/scripts/ch10.R
/usr/lib/R/library/MASS/scripts/ch16.R
/usr/lib/R/library/MASS/scripts/ch02.R
/usr/lib/R/library/MASS/scripts/ch06.R
/usr/lib/R/library/MASS/scripts/ch14.R
/usr/lib/R/library/MASS/scripts/ch09.R
/usr/lib/R/library/MASS/scripts/ch11.R
/usr/lib/R/library/MASS/scripts/ch15.R
/usr/lib/R/library/MASS/scripts/ch13.R
/usr/lib/R/library/MASS/scripts/ch12.R
/usr/lib/R/library/MASS/scripts/ch04.R
/usr/lib/R/library/MASS/scripts/ch05.R
/usr/lib/R/library/MASS/scripts/ch07.R
/usr/lib/R/library/MASS/data/Rdata.rdx
/usr/lib/R/library/MASS/data/Rdata.rds
/usr/lib/R/library/MASS/data/Rdata.rdb
/usr/lib/R/library/MASS/po/en@quot/LC_MESSAGES/R-MASS.mo
/usr/lib/R/library/MASS/po/it/LC_MESSAGES/R-MASS.mo
/usr/lib/R/library/MASS/po/fr/LC_MESSAGES/R-MASS.mo
/usr/lib/R/library/MASS/po/ko/LC_MESSAGES/R-MASS.mo
/usr/lib/R/library/MASS/po/de/LC_MESSAGES/R-MASS.mo
/usr/lib/R/library/MASS/po/pl/LC_MESSAGES/R-MASS.mo
/usr/lib/R/library/MASS/html/R.css
/usr/lib/R/library/MASS/html/00Index.html
/usr/lib/R/library/MASS/R/MASS.rdb
/usr/lib/R/library/MASS/R/MASS.rdx
/usr/lib/R/library/MASS/R/MASS
/usr/lib/R/library/MASS/DESCRIPTION
/usr/lib/R/library/MASS/libs/MASS.so
/usr/lib/R/library/MASS/CITATION
/usr/lib/R/library/MASS/help/MASS.rdb
/usr/lib/R/library/MASS/help/aliases.rds
/usr/lib/R/library/MASS/help/MASS.rdx
/usr/lib/R/library/MASS/help/AnIndex
/usr/lib/R/library/MASS/help/paths.rds
/usr/lib/R/library/MASS/NEWS
/usr/lib/R/library/MASS/Meta/Rd.rds
/usr/lib/R/library/MASS/Meta/data.rds
/usr/lib/R/library/MASS/Meta/links.rds
/usr/lib/R/library/MASS/Meta/features.rds
/usr/lib/R/library/MASS/Meta/package.rds
/usr/lib/R/library/MASS/Meta/hsearch.rds
/usr/lib/R/library/MASS/Meta/nsInfo.rds
/usr/lib/R/library/MASS/NAMESPACE
/usr/lib/R/library/splines/INDEX
/usr/lib/R/library/splines/html/R.css
/usr/lib/R/library/splines/html/00Index.html
/usr/lib/R/library/splines/R/splines.rdb
/usr/lib/R/library/splines/R/splines.rdx
/usr/lib/R/library/splines/R/splines
/usr/lib/R/library/splines/DESCRIPTION
/usr/lib/R/library/splines/libs/splines.so
/usr/lib/R/library/splines/help/splines.rdb
/usr/lib/R/library/splines/help/aliases.rds
/usr/lib/R/library/splines/help/splines.rdx
/usr/lib/R/library/splines/help/AnIndex
/usr/lib/R/library/splines/help/paths.rds
/usr/lib/R/library/splines/Meta/Rd.rds
/usr/lib/R/library/splines/Meta/links.rds
/usr/lib/R/library/splines/Meta/features.rds
/usr/lib/R/library/splines/Meta/package.rds
/usr/lib/R/library/splines/Meta/hsearch.rds
/usr/lib/R/library/splines/Meta/nsInfo.rds
/usr/lib/R/library/splines/NAMESPACE
/usr/lib/R/library/survival/doc/multi.pdf
/usr/lib/R/library/survival/doc/other.pdf
/usr/lib/R/library/survival/doc/compete.pdf
/usr/lib/R/library/survival/doc/timedep.Rnw
/usr/lib/R/library/survival/doc/other.Rnw
/usr/lib/R/library/survival/doc/survival.Rnw
/usr/lib/R/library/survival/doc/timedep.pdf
/usr/lib/R/library/survival/doc/methods.Rnw
/usr/lib/R/library/survival/doc/splines.pdf
/usr/lib/R/library/survival/doc/tiedtimes.R
/usr/lib/R/library/survival/doc/survival.R
/usr/lib/R/library/survival/doc/tiedtimes.Rnw
/usr/lib/R/library/survival/doc/approximate.Rnw
/usr/lib/R/library/survival/doc/compete.R
/usr/lib/R/library/survival/doc/methods.R
/usr/lib/R/library/survival/doc/population.Rnw
/usr/lib/R/library/survival/doc/methods.pdf
/usr/lib/R/library/survival/doc/validate.R
/usr/lib/R/library/survival/doc/population.pdf
/usr/lib/R/library/survival/doc/timedep.R
/usr/lib/R/library/survival/doc/multi.Rnw
/usr/lib/R/library/survival/doc/concordance.R
/usr/lib/R/library/survival/doc/matrix.Rnw
/usr/lib/R/library/survival/doc/matrix.pdf
/usr/lib/R/library/survival/doc/tiedtimes.pdf
/usr/lib/R/library/survival/doc/validate.Rnw
/usr/lib/R/library/survival/doc/index.html
/usr/lib/R/library/survival/doc/compete.Rnw
/usr/lib/R/library/survival/doc/validate.pdf
/usr/lib/R/library/survival/doc/redistribute.Rnw
/usr/lib/R/library/survival/doc/concordance.Rnw
/usr/lib/R/library/survival/doc/adjcurve.pdf
/usr/lib/R/library/survival/doc/adjcurve.Rnw
/usr/lib/R/library/survival/doc/splines.Rnw
/usr/lib/R/library/survival/doc/adjcurve.R
/usr/lib/R/library/survival/doc/survival.pdf
/usr/lib/R/library/survival/doc/matrix.R
/usr/lib/R/library/survival/doc/redistribute.R
/usr/lib/R/library/survival/doc/population.R
/usr/lib/R/library/survival/doc/approximate.R
/usr/lib/R/library/survival/doc/redistribute.pdf
/usr/lib/R/library/survival/doc/concordance.pdf
/usr/lib/R/library/survival/doc/approximate.pdf
/usr/lib/R/library/survival/doc/splines.R
/usr/lib/R/library/survival/INDEX
/usr/lib/R/library/survival/data/Rdata.rdx
/usr/lib/R/library/survival/data/Rdata.rds
/usr/lib/R/library/survival/data/Rdata.rdb
/usr/lib/R/library/survival/html/R.css
/usr/lib/R/library/survival/html/00Index.html
/usr/lib/R/library/survival/R/survival.rdb
/usr/lib/R/library/survival/R/survival.rdx
/usr/lib/R/library/survival/R/survival
/usr/lib/R/library/survival/DESCRIPTION
/usr/lib/R/library/survival/libs/survival.so
/usr/lib/R/library/survival/CITATION
/usr/lib/R/library/survival/help/aliases.rds
/usr/lib/R/library/survival/help/survival.rdb
/usr/lib/R/library/survival/help/survival.rdx
/usr/lib/R/library/survival/help/AnIndex
/usr/lib/R/library/survival/help/figures/logo.png
/usr/lib/R/library/survival/help/paths.rds
/usr/lib/R/library/survival/Meta/Rd.rds
/usr/lib/R/library/survival/Meta/data.rds
/usr/lib/R/library/survival/Meta/links.rds
/usr/lib/R/library/survival/Meta/vignette.rds
/usr/lib/R/library/survival/Meta/features.rds
/usr/lib/R/library/survival/Meta/package.rds
/usr/lib/R/library/survival/Meta/hsearch.rds
/usr/lib/R/library/survival/Meta/nsInfo.rds
/usr/lib/R/library/survival/NAMESPACE
/usr/lib/R/library/survival/COPYRIGHTS
/usr/lib/R/library/survival/NEWS.Rd
/usr/lib/R/library/tcltk/INDEX
/usr/lib/R/library/tcltk/exec/Tk-frontend.R
/usr/lib/R/library/tcltk/exec/util-string.tcl
/usr/lib/R/library/tcltk/exec/util.tcl
/usr/lib/R/library/tcltk/exec/pkgIndex.tcl
/usr/lib/R/library/tcltk/exec/console.tcl
/usr/lib/R/library/tcltk/exec/hierarchy.tcl
/usr/lib/R/library/tcltk/exec/util-tk.tcl
/usr/lib/R/library/tcltk/exec/util-dump.tcl
/usr/lib/R/library/tcltk/exec/progressbar.tcl
/usr/lib/R/library/tcltk/exec/util-number.tcl
/usr/lib/R/library/tcltk/exec/widget.tcl
/usr/lib/R/library/tcltk/exec/util-expand.tcl
/usr/lib/R/library/tcltk/html/R.css
/usr/lib/R/library/tcltk/html/00Index.html
/usr/lib/R/library/tcltk/R/tcltk
/usr/lib/R/library/tcltk/DESCRIPTION
/usr/lib/R/library/tcltk/help/tcltk.rdb
/usr/lib/R/library/tcltk/help/aliases.rds
/usr/lib/R/library/tcltk/help/tcltk.rdx
/usr/lib/R/library/tcltk/help/AnIndex
/usr/lib/R/library/tcltk/help/paths.rds
/usr/lib/R/library/tcltk/Meta/Rd.rds
/usr/lib/R/library/tcltk/Meta/links.rds
/usr/lib/R/library/tcltk/Meta/features.rds
/usr/lib/R/library/tcltk/Meta/package.rds
/usr/lib/R/library/tcltk/Meta/hsearch.rds
/usr/lib/R/library/tcltk/Meta/nsInfo.rds
/usr/lib/R/library/tcltk/Meta/demo.rds
/usr/lib/R/library/tcltk/NAMESPACE
/usr/lib/R/library/tcltk/demo/tkfaq.R
/usr/lib/R/library/tcltk/demo/tkcanvas.R
/usr/lib/R/library/tcltk/demo/tkdensity.R
/usr/lib/R/library/tcltk/demo/tkttest.R
/usr/lib/R/library/mgcv/INDEX
/usr/lib/R/library/mgcv/data/columb.rda
/usr/lib/R/library/mgcv/data/columb.polys.rda
/usr/lib/R/library/mgcv/po/en@quot/LC_MESSAGES/mgcv.mo
/usr/lib/R/library/mgcv/po/en@quot/LC_MESSAGES/R-mgcv.mo
/usr/lib/R/library/mgcv/po/fr/LC_MESSAGES/mgcv.mo
/usr/lib/R/library/mgcv/po/fr/LC_MESSAGES/R-mgcv.mo
/usr/lib/R/library/mgcv/po/ko/LC_MESSAGES/mgcv.mo
/usr/lib/R/library/mgcv/po/ko/LC_MESSAGES/R-mgcv.mo
/usr/lib/R/library/mgcv/po/de/LC_MESSAGES/mgcv.mo
/usr/lib/R/library/mgcv/po/de/LC_MESSAGES/R-mgcv.mo
/usr/lib/R/library/mgcv/po/pl/LC_MESSAGES/mgcv.mo
/usr/lib/R/library/mgcv/po/pl/LC_MESSAGES/R-mgcv.mo
/usr/lib/R/library/mgcv/html/R.css
/usr/lib/R/library/mgcv/html/00Index.html
/usr/lib/R/library/mgcv/R/mgcv.rdb
/usr/lib/R/library/mgcv/R/mgcv.rdx
/usr/lib/R/library/mgcv/R/mgcv
/usr/lib/R/library/mgcv/DESCRIPTION
/usr/lib/R/library/mgcv/libs/mgcv.so
/usr/lib/R/library/mgcv/CITATION
/usr/lib/R/library/mgcv/help/mgcv.rdb
/usr/lib/R/library/mgcv/help/mgcv.rdx
/usr/lib/R/library/mgcv/help/aliases.rds
/usr/lib/R/library/mgcv/help/AnIndex
/usr/lib/R/library/mgcv/help/paths.rds
/usr/lib/R/library/mgcv/Meta/Rd.rds
/usr/lib/R/library/mgcv/Meta/data.rds
/usr/lib/R/library/mgcv/Meta/links.rds
/usr/lib/R/library/mgcv/Meta/features.rds
/usr/lib/R/library/mgcv/Meta/package.rds
/usr/lib/R/library/mgcv/Meta/hsearch.rds
/usr/lib/R/library/mgcv/Meta/nsInfo.rds
/usr/lib/R/library/mgcv/NAMESPACE
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/en@quot/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/en_GB/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/bn/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/bn/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/bn/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/lt/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/it/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/da/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/sq/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/sq/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/tr/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/tr/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/tr/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/tr/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/tr/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/tr/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/tr/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/tr/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/DESCRIPTION
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/fr/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/nn/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/nn/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/nn/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/nn/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/ko/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/en/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/zh_CN/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/es/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/hi/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/ur/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/ne/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/ne/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/ne/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/ne/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/ne/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/ne/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/ne/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/ne/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/zh_TW/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/de/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/hu/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/ru/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/id/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/ja/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/pl/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/fa/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/fa/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/fa/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/fa/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/ar/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/pt_BR/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-methods.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/tools.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-tcltk.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-stats4.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-tools.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-grid.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/grDevices.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/methods.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/graphics.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-grDevices.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-splines.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-base.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-utils.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/splines.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/stats.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/tcltk.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/parallel.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-compiler.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-graphics.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/grid.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/RGui.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-stats.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/utils.mo
/usr/lib/R/library/translations/ca/LC_MESSAGES/R-parallel.mo
/usr/lib/R/library/methods/INDEX
/usr/lib/R/library/methods/html/R.css
/usr/lib/R/library/methods/html/00Index.html
/usr/lib/R/library/methods/R/methods.rdx
/usr/lib/R/library/methods/R/methods
/usr/lib/R/library/methods/R/methods.rdb
/usr/lib/R/library/methods/DESCRIPTION
/usr/lib/R/library/methods/libs/methods.so
/usr/lib/R/library/methods/help/methods.rdx
/usr/lib/R/library/methods/help/aliases.rds
/usr/lib/R/library/methods/help/AnIndex
/usr/lib/R/library/methods/help/methods.rdb
/usr/lib/R/library/methods/help/paths.rds
/usr/lib/R/library/methods/Meta/Rd.rds
/usr/lib/R/library/methods/Meta/links.rds
/usr/lib/R/library/methods/Meta/features.rds
/usr/lib/R/library/methods/Meta/package.rds
/usr/lib/R/library/methods/Meta/hsearch.rds
/usr/lib/R/library/methods/Meta/nsInfo.rds
/usr/lib/R/library/methods/NAMESPACE
/usr/lib/R/library/datasets/INDEX
/usr/lib/R/library/datasets/data/Rdata.rdx
/usr/lib/R/library/datasets/data/Rdata.rds
/usr/lib/R/library/datasets/data/Rdata.rdb
/usr/lib/R/library/datasets/data/morley.tab
/usr/lib/R/library/datasets/html/R.css
/usr/lib/R/library/datasets/html/00Index.html
/usr/lib/R/library/datasets/DESCRIPTION
/usr/lib/R/library/datasets/help/datasets.rdx
/usr/lib/R/library/datasets/help/aliases.rds
/usr/lib/R/library/datasets/help/AnIndex
/usr/lib/R/library/datasets/help/datasets.rdb
/usr/lib/R/library/datasets/help/paths.rds
/usr/lib/R/library/datasets/Meta/Rd.rds
/usr/lib/R/library/datasets/Meta/data.rds
/usr/lib/R/library/datasets/Meta/links.rds
/usr/lib/R/library/datasets/Meta/features.rds
/usr/lib/R/library/datasets/Meta/package.rds
/usr/lib/R/library/datasets/Meta/hsearch.rds
/usr/lib/R/library/datasets/Meta/nsInfo.rds
/usr/lib/R/library/datasets/NAMESPACE
/usr/lib/R/library/cluster/INDEX
/usr/lib/R/library/cluster/data/Rdata.rdx
/usr/lib/R/library/cluster/data/Rdata.rds
/usr/lib/R/library/cluster/data/Rdata.rdb
/usr/lib/R/library/cluster/po/en@quot/LC_MESSAGES/cluster.mo
/usr/lib/R/library/cluster/po/en@quot/LC_MESSAGES/R-cluster.mo
/usr/lib/R/library/cluster/po/lt/LC_MESSAGES/cluster.mo
/usr/lib/R/library/cluster/po/lt/LC_MESSAGES/R-cluster.mo
/usr/lib/R/library/cluster/po/it/LC_MESSAGES/cluster.mo
/usr/lib/R/library/cluster/po/it/LC_MESSAGES/R-cluster.mo
/usr/lib/R/library/cluster/po/fr/LC_MESSAGES/cluster.mo
/usr/lib/R/library/cluster/po/fr/LC_MESSAGES/R-cluster.mo
/usr/lib/R/library/cluster/po/ko/LC_MESSAGES/cluster.mo
/usr/lib/R/library/cluster/po/ko/LC_MESSAGES/R-cluster.mo
/usr/lib/R/library/cluster/po/de/LC_MESSAGES/cluster.mo
/usr/lib/R/library/cluster/po/de/LC_MESSAGES/R-cluster.mo
/usr/lib/R/library/cluster/po/pl/LC_MESSAGES/R-cluster.mo
/usr/lib/R/library/cluster/html/R.css
/usr/lib/R/library/cluster/html/00Index.html
/usr/lib/R/library/cluster/R/cluster.rdb
/usr/lib/R/library/cluster/R/cluster.rdx
/usr/lib/R/library/cluster/R/cluster
/usr/lib/R/library/cluster/DESCRIPTION
/usr/lib/R/library/cluster/libs/cluster.so
/usr/lib/R/library/cluster/CITATION
/usr/lib/R/library/cluster/help/cluster.rdb
/usr/lib/R/library/cluster/help/aliases.rds
/usr/lib/R/library/cluster/help/cluster.rdx
/usr/lib/R/library/cluster/help/AnIndex
/usr/lib/R/library/cluster/help/paths.rds
/usr/lib/R/library/cluster/Meta/Rd.rds
/usr/lib/R/library/cluster/Meta/data.rds
/usr/lib/R/library/cluster/Meta/links.rds
/usr/lib/R/library/cluster/Meta/features.rds
/usr/lib/R/library/cluster/Meta/package.rds
/usr/lib/R/library/cluster/Meta/hsearch.rds
/usr/lib/R/library/cluster/Meta/nsInfo.rds
/usr/lib/R/library/cluster/NAMESPACE
/usr/lib/R/library/cluster/test-tools.R
/usr/lib/R/library/cluster/NEWS.Rd
/usr/lib/R/SVN-REVISION
/usr/lib/R/include
/usr/lib/R/include/Rconfig.h
/usr/lib/R/include/Rembedded.h
/usr/lib/R/include/Rdefines.h
/usr/lib/R/include/R_ext
/usr/lib/R/include/R_ext/Arith.h
/usr/lib/R/include/R_ext/GetX11Image.h
/usr/lib/R/include/R_ext/Rdynload.h
/usr/lib/R/include/R_ext/Boolean.h
/usr/lib/R/include/R_ext/Itermacros.h
/usr/lib/R/include/R_ext/stats_stubs.h
/usr/lib/R/include/R_ext/Linpack.h
/usr/lib/R/include/R_ext/Utils.h
/usr/lib/R/include/R_ext/GraphicsDevice.h
/usr/lib/R/include/R_ext/RStartup.h
/usr/lib/R/include/R_ext/libextern.h
/usr/lib/R/include/R_ext/stats_package.h
/usr/lib/R/include/R_ext/Altrep.h
/usr/lib/R/include/R_ext/Random.h
/usr/lib/R/include/R_ext/ObjectTable.h
/usr/lib/R/include/R_ext/Memory.h
/usr/lib/R/include/R_ext/Lapack.h
/usr/lib/R/include/R_ext/GraphicsEngine.h
/usr/lib/R/include/R_ext/Riconv.h
/usr/lib/R/include/R_ext/Constants.h
/usr/lib/R/include/R_ext/QuartzDevice.h
/usr/lib/R/include/R_ext/Print.h
/usr/lib/R/include/R_ext/Parse.h
/usr/lib/R/include/R_ext/Rallocators.h
/usr/lib/R/include/R_ext/Complex.h
/usr/lib/R/include/R_ext/BLAS.h
/usr/lib/R/include/R_ext/Callbacks.h
/usr/lib/R/include/R_ext/Error.h
/usr/lib/R/include/R_ext/eventloop.h
/usr/lib/R/include/R_ext/Connections.h
/usr/lib/R/include/R_ext/RS.h
/usr/lib/R/include/R_ext/MathThreads.h
/usr/lib/R/include/R_ext/Visibility.h
/usr/lib/R/include/R_ext/Applic.h
/usr/lib/R/include/Rinterface.h
/usr/lib/R/include/R.h
/usr/lib/R/include/Rversion.h
/usr/lib/R/include/Rinternals.h
/usr/lib/R/include/Rmath.h
/usr/share/doc/R-4.6.1
/usr/share/doc/R-4.6.1/COPYING
/usr/share/doc/R-4.6.1/AUTHORS
/usr/share/doc/R-4.6.1/NEWS.1
/usr/share/doc/R-4.6.1/NEWS.pdf
/usr/share/doc/R-4.6.1/NEWS.2.rds
/usr/share/doc/R-4.6.1/NEWS.3
/usr/share/doc/R-4.6.1/html
/usr/share/doc/R-4.6.1/html/resources.html
/usr/share/doc/R-4.6.1/html/up.jpg
/usr/share/doc/R-4.6.1/html/NEWS.3.html
/usr/share/doc/R-4.6.1/html/mathjax-config.js
/usr/share/doc/R-4.6.1/html/prism.css
/usr/share/doc/R-4.6.1/html/favicon.ico
/usr/share/doc/R-4.6.1/html/prism.js
/usr/share/doc/R-4.6.1/html/katex-config.js
/usr/share/doc/R-4.6.1/html/about.html
/usr/share/doc/R-4.6.1/html/katex
/usr/share/doc/R-4.6.1/html/katex/katex.css
/usr/share/doc/R-4.6.1/html/katex/fonts
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Size2-Regular.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Main-Italic.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_AMS-Regular.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Fraktur-Regular.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_AMS-Regular.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Math-BoldItalic.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Caligraphic-Regular.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Size2-Regular.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Caligraphic-Regular.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Main-Italic.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Math-BoldItalic.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Math-BoldItalic.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Caligraphic-Bold.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_SansSerif-Italic.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Main-Italic.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_SansSerif-Bold.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Size3-Regular.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Size3-Regular.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Size1-Regular.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Main-BoldItalic.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_SansSerif-Bold.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Main-Bold.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Main-Regular.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Size1-Regular.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Math-Italic.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_SansSerif-Bold.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Main-BoldItalic.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Fraktur-Regular.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_SansSerif-Italic.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Main-Bold.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Main-BoldItalic.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Script-Regular.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Fraktur-Bold.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Caligraphic-Bold.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Typewriter-Regular.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Fraktur-Bold.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Typewriter-Regular.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Main-Regular.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Size1-Regular.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_SansSerif-Regular.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Size4-Regular.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Caligraphic-Bold.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Size4-Regular.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Size3-Regular.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Fraktur-Regular.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Math-Italic.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Size2-Regular.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Main-Regular.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_AMS-Regular.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Script-Regular.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Math-Italic.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_SansSerif-Regular.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Script-Regular.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Size4-Regular.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_SansSerif-Regular.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Typewriter-Regular.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Caligraphic-Regular.woff
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Main-Bold.woff2
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_SansSerif-Italic.ttf
/usr/share/doc/R-4.6.1/html/katex/fonts/KaTeX_Fraktur-Bold.ttf
/usr/share/doc/R-4.6.1/html/katex/LICENSE
/usr/share/doc/R-4.6.1/html/katex/katex.js
/usr/share/doc/R-4.6.1/html/katex/README.md
/usr/share/doc/R-4.6.1/html/ror.svg
/usr/share/doc/R-4.6.1/html/Rlogo.pdf
/usr/share/doc/R-4.6.1/html/Rlogo.svg
/usr/share/doc/R-4.6.1/html/right.jpg
/usr/share/doc/R-4.6.1/html/orcid.svg
/usr/share/doc/R-4.6.1/html/R.css
/usr/share/doc/R-4.6.1/html/index.html
/usr/share/doc/R-4.6.1/html/NEWS.2.html
/usr/share/doc/R-4.6.1/html/Search.html
/usr/share/doc/R-4.6.1/html/left.jpg
/usr/share/doc/R-4.6.1/html/R-nav.css
/usr/share/doc/R-4.6.1/html/NEWS.html
/usr/share/doc/R-4.6.1/html/logo.jpg
/usr/share/doc/R-4.6.1/html/SearchOn.html
/usr/share/doc/R-4.6.1/html/packages-head-utf8.html
/usr/share/doc/R-4.6.1/html/packages.html
/usr/share/doc/R-4.6.1/html/katex-check.js
/usr/share/doc/R-4.6.1/VERSION
/usr/share/doc/R-4.6.1/README
/usr/share/doc/R-4.6.1/CRAN_mirrors.csv
/usr/share/doc/R-4.6.1/VERSION-NICK
/usr/share/doc/R-4.6.1/NEWS
/usr/share/doc/R-4.6.1/KEYWORDS.db
/usr/share/doc/R-4.6.1/COPYRIGHTS
/usr/share/doc/R-4.6.1/NEWS.3.rds
/usr/share/doc/R-4.6.1/NEWS.rds
/usr/share/doc/R-4.6.1/FAQ
/usr/share/doc/R-4.6.1/NEWS.0
/usr/share/doc/R-4.6.1/SVN-REVISION
/usr/share/doc/R-4.6.1/manual
/usr/share/doc/R-4.6.1/manual/R-data.html
/usr/share/doc/R-4.6.1/manual/R-lang.html
/usr/share/doc/R-4.6.1/manual/images
/usr/share/doc/R-4.6.1/manual/images/ice.png
/usr/share/doc/R-4.6.1/manual/images/hist.png
/usr/share/doc/R-4.6.1/manual/images/ecdf.png
/usr/share/doc/R-4.6.1/manual/images/fig11.png
/usr/share/doc/R-4.6.1/manual/images/QQ.png
/usr/share/doc/R-4.6.1/manual/images/fig12.png
/usr/share/doc/R-4.6.1/manual/R-ints.html
/usr/share/doc/R-4.6.1/manual/R-FAQ.html
/usr/share/doc/R-4.6.1/manual/R-exts.html
/usr/share/doc/R-4.6.1/manual/R-admin.html
/usr/share/doc/R-4.6.1/manual/R-intro.html
/usr/share/doc/R-4.6.1/BioC_mirrors.csv
/usr/share/doc/R-4.6.1/KEYWORDS
/usr/share/doc/R-4.6.1/THANKS
/usr/share/doc/R-4.6.1/RESOURCES
/usr/share/doc/R-4.6.1/NEWS.2
/usr/share/applications
/usr/share/applications/R.desktop
/usr/bin
/usr/bin/R
/usr/bin/Rscript
/usr/man/man1
/usr/man/man1/R.1
/usr/man/man1/Rscript.1
